//! Safe owner for platform W^X executable-memory mappings.
//!
//! This module sits below the data-only executable-memory residency records. It
//! allocates writable memory, copies generated bytes while the mapping is
//! writable, seals the mapping read/execute, and releases the mapping exactly
//! once through a safe state machine. It does not expose executable addresses or
//! function pointers. The only generated-code invocation supported here is the
//! sealed P6 x86_64 C-ABI entry helper, which keeps the raw executable address
//! private to the platform backend.

use std::ffi::c_void;
use std::fmt;
use std::ptr::NonNull;

use crate::jit::{
    ExecutableAllocationId, ExecutableAllocationLifecycle, ExecutableAllocationRecord,
    ExecutableAllocationRequest, ExecutableLedgerValidationError, ExecutableMemoryProtection,
    ExecutableMutationAuthority, MachineCodeHandle, MachineCodeOwnership, MachineCodeRange,
    MachineCodeValidationError,
};

use super::executable_memory::{
    ExecutableMemoryMappedRange, ExecutableMemoryPageSize, ExecutableMemoryResidencyValidationError,
};

#[cfg(unix)]
use super::unix_executable_memory;

#[cfg(unix)]
type PlatformExecutableMemoryMapping = unix_executable_memory::ExecutableMemoryMapping;

/// Request for one platform-owned executable-memory compartment.
///
/// `range` names the machine-code bytes inside the allocation. The platform
/// mapping starts at offset zero and is rounded up to whole pages so this range
/// can be copied and then protected RX.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ExecutableMemoryCompartmentRequest {
    pub allocation: ExecutableAllocationId,
    pub owner: MachineCodeOwnership,
    pub range: MachineCodeRange,
    pub mutation_authority: ExecutableMutationAuthority,
}

/// Request to invoke a sealed P6 C-ABI entry inside an RX compartment.
///
/// `entry_offset` is an allocation-relative offset. The opaque VM and frame-base
/// pointers are passed through to generated code without exposing the
/// executable address to callers. `callee_value_bits` is Rust's current native
/// carrier for JSC's active call-frame callee slot while the raw frame base
/// still points at local0 rather than a full JSC-compatible frame header.
/// `ic_store_base` is the baseline data-IC record store base, passed as the 4th
/// C-ABI argument (rcx); the P6 prologue seeds it into r13
/// (GPRInfo::jitDataRegister). It is a dangling pointer when the CodeBlock has
/// zero IC sites, in which case generated code never dereferences it (the entry
/// only moves it into the callee-saved r13).
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ExecutableMemoryP6CallRequest {
    pub entry_offset: u32,
    pub vm: NonNull<c_void>,
    pub frame_base: NonNull<c_void>,
    pub callee_value_bits: u64,
    pub ic_store_base: NonNull<c_void>,
}

/// Request shape for a future ARM64 JSC stack-call trampoline.
///
/// C++ `LowLevelInterpreter64.asm` `_llint_call_javascript` enters generated
/// code with `sp = CallFrame + sizeof(CallerFrameAndPC)`. The generated ARM64
/// prologue then pushes `fp/lr`, making `fp/x29` equal the callee `CallFrame*`.
/// This request carries that checked stack-entry pointer; it is not the current
/// raw Rust register-window C ABI frame pointer.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ExecutableMemoryArm64JscStackCallRequest {
    pub entry_offset: u32,
    pub entry_sp: NonNull<c_void>,
    pub call_frame: NonNull<c_void>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ExecutableMemoryArm64JscStackCallRequestValidationError {
    CallFrameUnaligned {
        call_frame: usize,
    },
    EntryStackPointerOverflow {
        call_frame: usize,
    },
    EntryStackPointerMismatch {
        expected_entry_sp: usize,
        actual_entry_sp: usize,
    },
}

/// Request to invoke a result-seeded P9 owner post-call reentry stub.
///
/// `result_bits` is passed as the third C-ABI argument so the reentry stub can
/// move it into the platform return-value register. `metadata_table_base` is
/// passed as the fourth C-ABI argument for post-call profile stores that use
/// JSC's metadata-table register shape before joining the owner post-call
/// block. `callee_value_bits` is passed as the fifth C-ABI argument and seeded
/// into the same Rust callee carrier used by ordinary P6 entry.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ExecutableMemoryP9PostCallReentryRequest {
    pub entry_offset: u32,
    pub vm: NonNull<c_void>,
    pub frame_base: NonNull<c_void>,
    pub result_bits: u64,
    pub metadata_table_base: NonNull<c_void>,
    pub callee_value_bits: u64,
}

/// Raw EncodedJsValue bits returned by a sealed P6 call.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ExecutableMemoryP6CallResult {
    pub encoded_js_value_bits: u64,
}

/// Platform operation that can fail while managing executable memory.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ExecutableMemoryPlatformOperation {
    QueryPageSize,
    AllocateWritable,
    CopyBytes,
    ProtectExecutable,
    CallP6Entry,
    CallP9PostCallReentry,
    Release,
    ReadBytesForTesting,
}

/// Safe API errors for the platform-owned W^X compartment.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ExecutableMemoryCompartmentError {
    UnsupportedPlatform,
    AllocationLedgerInvalid {
        reason: ExecutableLedgerValidationError,
    },
    PageSizeInvalid {
        page_size: i64,
    },
    MappedLengthOverflow {
        range: MachineCodeRange,
        page_size: ExecutableMemoryPageSize,
    },
    MappedRangeInvalid {
        reason: ExecutableMemoryResidencyValidationError,
    },
    RangeInvalid {
        error: MachineCodeValidationError,
    },
    ByteCopyLengthMismatch {
        expected: usize,
        actual: usize,
    },
    ByteLengthTooLarge {
        actual: usize,
    },
    WrongProtection {
        expected: ExecutableMemoryProtection,
        actual: ExecutableMemoryProtection,
    },
    WrongLifecycle {
        expected: ExecutableAllocationLifecycle,
        actual: ExecutableAllocationLifecycle,
    },
    EntryOffsetOutOfRange {
        entry_offset: u32,
        range: MachineCodeRange,
    },
    AlreadyReleased,
    PlatformFailure {
        operation: ExecutableMemoryPlatformOperation,
        errno: Option<i32>,
    },
}

/// Platform-owned executable-memory compartment with a safe W^X state machine.
pub struct ExecutableMemoryCompartment {
    allocation: ExecutableAllocationId,
    owner: MachineCodeOwnership,
    machine_range: MachineCodeRange,
    mapped_range: ExecutableMemoryMappedRange,
    protection: ExecutableMemoryProtection,
    lifecycle: ExecutableAllocationLifecycle,
    mutation_authority: ExecutableMutationAuthority,
    #[cfg(unix)]
    mapping: Option<PlatformExecutableMemoryMapping>,
}

impl ExecutableMemoryCompartmentRequest {
    pub const fn new(
        allocation: ExecutableAllocationId,
        owner: MachineCodeOwnership,
        byte_len: u32,
    ) -> Self {
        Self::with_range(
            allocation,
            owner,
            MachineCodeRange {
                allocation,
                start_offset: 0,
                size_bytes: byte_len,
            },
            ExecutableMutationAuthority::LinkBuffer,
        )
    }

    pub const fn with_range(
        allocation: ExecutableAllocationId,
        owner: MachineCodeOwnership,
        range: MachineCodeRange,
        mutation_authority: ExecutableMutationAuthority,
    ) -> Self {
        Self {
            allocation,
            owner,
            range,
            mutation_authority,
        }
    }

    fn allocation_request(self) -> ExecutableAllocationRequest {
        ExecutableAllocationRequest {
            allocation: self.allocation,
            owner: self.owner,
            byte_len: self.range.size_bytes,
            range: self.range,
            protection: ExecutableMemoryProtection::Writable,
            lifecycle: ExecutableAllocationLifecycle::AllocatedWritable,
            mutation_authority: self.mutation_authority,
        }
    }
}

impl ExecutableMemoryP6CallRequest {
    pub const fn new(
        entry_offset: u32,
        vm: NonNull<c_void>,
        frame_base: NonNull<c_void>,
        callee_value_bits: u64,
        ic_store_base: NonNull<c_void>,
    ) -> Self {
        Self {
            entry_offset,
            vm,
            frame_base,
            callee_value_bits,
            ic_store_base,
        }
    }
}

impl ExecutableMemoryArm64JscStackCallRequest {
    pub const CALLER_FRAME_AND_PC_BYTES: usize = 16;
    pub const STACK_ALIGNMENT_BYTES: usize = 16;

    pub const fn new(
        entry_offset: u32,
        entry_sp: NonNull<c_void>,
        call_frame: NonNull<c_void>,
    ) -> Self {
        Self {
            entry_offset,
            entry_sp,
            call_frame,
        }
    }

    pub fn validate(self) -> Result<(), ExecutableMemoryArm64JscStackCallRequestValidationError> {
        let call_frame = self.call_frame.as_ptr() as usize;
        if call_frame % Self::STACK_ALIGNMENT_BYTES != 0 {
            return Err(
                ExecutableMemoryArm64JscStackCallRequestValidationError::CallFrameUnaligned {
                    call_frame,
                },
            );
        }
        let Some(expected_entry_sp) = call_frame.checked_add(Self::CALLER_FRAME_AND_PC_BYTES)
        else {
            return Err(
                ExecutableMemoryArm64JscStackCallRequestValidationError::EntryStackPointerOverflow {
                    call_frame,
                },
            );
        };
        let actual_entry_sp = self.entry_sp.as_ptr() as usize;
        if actual_entry_sp != expected_entry_sp {
            return Err(
                ExecutableMemoryArm64JscStackCallRequestValidationError::EntryStackPointerMismatch {
                    expected_entry_sp,
                    actual_entry_sp,
                },
            );
        }
        Ok(())
    }
}

impl ExecutableMemoryP9PostCallReentryRequest {
    pub const fn new(
        entry_offset: u32,
        vm: NonNull<c_void>,
        frame_base: NonNull<c_void>,
        result_bits: u64,
        metadata_table_base: NonNull<c_void>,
        callee_value_bits: u64,
    ) -> Self {
        Self {
            entry_offset,
            vm,
            frame_base,
            result_bits,
            metadata_table_base,
            callee_value_bits,
        }
    }
}

impl fmt::Debug for ExecutableMemoryCompartment {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        let mut debug = formatter.debug_struct("ExecutableMemoryCompartment");
        debug
            .field("allocation", &self.allocation)
            .field("owner", &self.owner)
            .field("machine_range", &self.machine_range)
            .field("mapped_range", &self.mapped_range)
            .field("protection", &self.protection)
            .field("lifecycle", &self.lifecycle)
            .field("mutation_authority", &self.mutation_authority);
        #[cfg(unix)]
        debug.field("mapped", &self.mapping.is_some());
        debug.finish()
    }
}

impl ExecutableMemoryCompartment {
    /// Allocate a writable, non-executable platform mapping for `request`.
    #[cfg(unix)]
    pub fn allocate(
        request: ExecutableMemoryCompartmentRequest,
    ) -> Result<Self, ExecutableMemoryCompartmentError> {
        let allocation_request = request.allocation_request();
        allocation_request.validate().map_err(|reason| {
            ExecutableMemoryCompartmentError::AllocationLedgerInvalid { reason }
        })?;

        let page_size = platform_page_size()?;
        let mapped_byte_len = mapped_byte_len_for_range(request.range, page_size)?;
        let mapped_range = ExecutableMemoryMappedRange {
            allocation: request.allocation,
            start_offset: 0,
            byte_len: mapped_byte_len,
            page_size,
        };
        mapped_range
            .validate()
            .map_err(|reason| ExecutableMemoryCompartmentError::MappedRangeInvalid { reason })?;
        mapped_range
            .contains_machine_range(request.range)
            .map_err(|reason| ExecutableMemoryCompartmentError::MappedRangeInvalid { reason })?;

        let mapping = PlatformExecutableMemoryMapping::allocate_writable(mapped_byte_len as usize)
            .map_err(map_platform_error)?;

        Ok(Self {
            allocation: request.allocation,
            owner: request.owner,
            machine_range: request.range,
            mapped_range,
            protection: ExecutableMemoryProtection::Writable,
            lifecycle: ExecutableAllocationLifecycle::AllocatedWritable,
            mutation_authority: request.mutation_authority,
            mapping: Some(mapping),
        })
    }

    /// Return `UnsupportedPlatform` on non-Unix targets without attempting to
    /// emulate executable mappings.
    #[cfg(not(unix))]
    pub fn allocate(
        _request: ExecutableMemoryCompartmentRequest,
    ) -> Result<Self, ExecutableMemoryCompartmentError> {
        Err(ExecutableMemoryCompartmentError::UnsupportedPlatform)
    }

    pub fn allocation(&self) -> ExecutableAllocationId {
        self.allocation
    }

    pub fn owner(&self) -> MachineCodeOwnership {
        self.owner
    }

    pub fn machine_range(&self) -> MachineCodeRange {
        self.machine_range
    }

    pub fn mapped_range(&self) -> ExecutableMemoryMappedRange {
        self.mapped_range
    }

    pub fn protection(&self) -> ExecutableMemoryProtection {
        self.protection
    }

    pub fn lifecycle(&self) -> ExecutableAllocationLifecycle {
        self.lifecycle
    }

    pub fn mutation_authority(&self) -> ExecutableMutationAuthority {
        self.mutation_authority
    }

    pub fn allocation_record(&self) -> ExecutableAllocationRecord {
        ExecutableAllocationRecord::from_request(ExecutableAllocationRequest {
            allocation: self.allocation,
            owner: self.owner,
            byte_len: self.machine_range.size_bytes,
            range: self.machine_range,
            protection: self.protection,
            lifecycle: self.lifecycle,
            mutation_authority: self.mutation_authority,
        })
    }

    /// Copy generated bytes into a mapped range while the compartment is
    /// writable. This refuses writes after RX protection or release.
    pub fn copy_from_slice(
        &mut self,
        range: MachineCodeRange,
        bytes: &[u8],
    ) -> Result<(), ExecutableMemoryCompartmentError> {
        self.require_protection(ExecutableMemoryProtection::Writable)?;
        self.validate_mapped_machine_range(range)?;
        if bytes.len() > u32::MAX as usize {
            return Err(ExecutableMemoryCompartmentError::ByteLengthTooLarge {
                actual: bytes.len(),
            });
        }
        let expected = range.size_bytes as usize;
        if bytes.len() != expected {
            return Err(ExecutableMemoryCompartmentError::ByteCopyLengthMismatch {
                expected,
                actual: bytes.len(),
            });
        }

        #[cfg(unix)]
        {
            let mapping = self
                .mapping
                .as_ref()
                .ok_or(ExecutableMemoryCompartmentError::AlreadyReleased)?;
            mapping
                .copy_from_slice(range.start_offset as usize, bytes)
                .map_err(map_platform_error)
        }
        #[cfg(not(unix))]
        {
            let _ = bytes;
            Err(ExecutableMemoryCompartmentError::UnsupportedPlatform)
        }
    }

    /// Seal the mapping RX. The safe API has no transition back to writable.
    pub fn protect_executable(&mut self) -> Result<(), ExecutableMemoryCompartmentError> {
        self.require_protection(ExecutableMemoryProtection::Writable)?;

        #[cfg(unix)]
        {
            let mapping = self
                .mapping
                .as_ref()
                .ok_or(ExecutableMemoryCompartmentError::AlreadyReleased)?;
            mapping.protect_executable().map_err(map_platform_error)?;
            self.protection = ExecutableMemoryProtection::Executable;
            self.lifecycle = ExecutableAllocationLifecycle::LinkedExecutable;
            Ok(())
        }
        #[cfg(not(unix))]
        {
            Err(ExecutableMemoryCompartmentError::UnsupportedPlatform)
        }
    }

    /// Return an opaque machine-code handle only after the mapping is RX.
    ///
    /// The handle carries the allocation identity and range, not an executable
    /// address or callable function pointer.
    pub fn executable_machine_code_handle(
        &self,
    ) -> Result<MachineCodeHandle, ExecutableMemoryCompartmentError> {
        self.require_protection(ExecutableMemoryProtection::Executable)?;
        let handle = MachineCodeHandle {
            allocation: self.allocation,
            owner: self.owner,
            range: self.machine_range,
            symbol: None,
            protection: self.protection,
            lifecycle: self.lifecycle,
            mutation_authority: self.mutation_authority,
        };
        handle
            .validate()
            .map_err(|error| ExecutableMemoryCompartmentError::RangeInvalid { error })?;
        Ok(handle)
    }

    /// Invoke a sealed P6 x86_64 C-ABI entry inside an already RX compartment.
    ///
    /// The executable address and function pointer remain private to the
    /// platform backend. This wrapper only accepts opaque VM/frame-base
    /// pointers and returns raw EncodedJsValue bits.
    pub fn call_p6_x86_64_entry(
        &self,
        request: ExecutableMemoryP6CallRequest,
    ) -> Result<ExecutableMemoryP6CallResult, ExecutableMemoryCompartmentError> {
        self.require_executable_lifecycle()?;
        self.validate_entry_offset(request.entry_offset)?;

        #[cfg(all(unix, target_arch = "x86_64"))]
        {
            let mapping = self
                .mapping
                .as_ref()
                .ok_or(ExecutableMemoryCompartmentError::AlreadyReleased)?;
            let encoded_js_value_bits = mapping
                .call_p6_x86_64_entry(
                    request.entry_offset as usize,
                    request.vm,
                    request.frame_base,
                    request.callee_value_bits,
                    request.ic_store_base,
                )
                .map_err(|error| {
                    map_call_platform_error(error, ExecutableMemoryPlatformOperation::CallP6Entry)
                })?;
            Ok(ExecutableMemoryP6CallResult {
                encoded_js_value_bits,
            })
        }
        #[cfg(any(not(unix), not(target_arch = "x86_64")))]
        {
            let _ = request;
            Err(ExecutableMemoryCompartmentError::UnsupportedPlatform)
        }
    }

    /// Invoke a sealed P6 ARM64 C-ABI entry inside an already RX compartment.
    ///
    /// The executable address and function pointer remain private to the
    /// platform backend. This wrapper only accepts opaque VM/frame-base
    /// pointers and returns raw EncodedJsValue bits.
    pub fn call_p6_arm64_entry(
        &self,
        request: ExecutableMemoryP6CallRequest,
    ) -> Result<ExecutableMemoryP6CallResult, ExecutableMemoryCompartmentError> {
        self.require_executable_lifecycle()?;
        self.validate_entry_offset(request.entry_offset)?;

        #[cfg(all(unix, target_arch = "aarch64"))]
        {
            let mapping = self
                .mapping
                .as_ref()
                .ok_or(ExecutableMemoryCompartmentError::AlreadyReleased)?;
            let encoded_js_value_bits = mapping
                .call_p6_arm64_entry(
                    request.entry_offset as usize,
                    request.vm,
                    request.frame_base,
                    request.callee_value_bits,
                    request.ic_store_base,
                )
                .map_err(|error| {
                    map_call_platform_error(error, ExecutableMemoryPlatformOperation::CallP6Entry)
                })?;
            Ok(ExecutableMemoryP6CallResult {
                encoded_js_value_bits,
            })
        }
        #[cfg(any(not(unix), not(target_arch = "aarch64")))]
        {
            let _ = request;
            Err(ExecutableMemoryCompartmentError::UnsupportedPlatform)
        }
    }

    pub fn call_p9_x86_64_owner_post_call_reentry(
        &self,
        request: ExecutableMemoryP9PostCallReentryRequest,
    ) -> Result<ExecutableMemoryP6CallResult, ExecutableMemoryCompartmentError> {
        self.require_executable_lifecycle()?;
        self.validate_entry_offset(request.entry_offset)?;

        #[cfg(all(unix, target_arch = "x86_64"))]
        {
            let mapping = self
                .mapping
                .as_ref()
                .ok_or(ExecutableMemoryCompartmentError::AlreadyReleased)?;
            let encoded_js_value_bits = mapping
                .call_p9_x86_64_owner_post_call_reentry(
                    request.entry_offset as usize,
                    request.vm,
                    request.frame_base,
                    request.result_bits,
                    request.metadata_table_base,
                    request.callee_value_bits,
                )
                .map_err(|error| {
                    map_call_platform_error(
                        error,
                        ExecutableMemoryPlatformOperation::CallP9PostCallReentry,
                    )
                })?;
            Ok(ExecutableMemoryP6CallResult {
                encoded_js_value_bits,
            })
        }
        #[cfg(any(not(unix), not(target_arch = "x86_64")))]
        {
            let _ = request;
            Err(ExecutableMemoryCompartmentError::UnsupportedPlatform)
        }
    }

    /// Release the platform mapping. Releasing twice, writing after release, or
    /// protecting after release is rejected by the safe state.
    pub fn release(&mut self) -> Result<(), ExecutableMemoryCompartmentError> {
        if self.lifecycle == ExecutableAllocationLifecycle::Released {
            return Err(ExecutableMemoryCompartmentError::AlreadyReleased);
        }

        #[cfg(unix)]
        {
            let mapping = self
                .mapping
                .as_mut()
                .ok_or(ExecutableMemoryCompartmentError::AlreadyReleased)?;
            mapping.release().map_err(map_platform_error)?;
            self.mapping = None;
            self.protection = ExecutableMemoryProtection::Decommitted;
            self.lifecycle = ExecutableAllocationLifecycle::Released;
            self.mutation_authority = ExecutableMutationAuthority::AllocatorOnly;
            Ok(())
        }
        #[cfg(not(unix))]
        {
            Err(ExecutableMemoryCompartmentError::UnsupportedPlatform)
        }
    }

    fn require_protection(
        &self,
        expected: ExecutableMemoryProtection,
    ) -> Result<(), ExecutableMemoryCompartmentError> {
        if self.lifecycle == ExecutableAllocationLifecycle::Released {
            return Err(ExecutableMemoryCompartmentError::AlreadyReleased);
        }
        if self.protection != expected {
            return Err(ExecutableMemoryCompartmentError::WrongProtection {
                expected,
                actual: self.protection,
            });
        }
        Ok(())
    }

    fn require_executable_lifecycle(&self) -> Result<(), ExecutableMemoryCompartmentError> {
        self.require_protection(ExecutableMemoryProtection::Executable)?;
        if self.lifecycle != ExecutableAllocationLifecycle::LinkedExecutable {
            return Err(ExecutableMemoryCompartmentError::WrongLifecycle {
                expected: ExecutableAllocationLifecycle::LinkedExecutable,
                actual: self.lifecycle,
            });
        }
        Ok(())
    }

    fn validate_mapped_machine_range(
        &self,
        range: MachineCodeRange,
    ) -> Result<(), ExecutableMemoryCompartmentError> {
        range
            .validate()
            .map_err(|error| ExecutableMemoryCompartmentError::RangeInvalid { error })?;
        self.mapped_range
            .contains_machine_range(range)
            .map_err(|reason| ExecutableMemoryCompartmentError::MappedRangeInvalid { reason })
    }

    fn validate_entry_offset(
        &self,
        entry_offset: u32,
    ) -> Result<(), ExecutableMemoryCompartmentError> {
        let end_offset = self.machine_range.end_offset().ok_or(
            ExecutableMemoryCompartmentError::RangeInvalid {
                error: MachineCodeValidationError::RangeEndOverflow,
            },
        )?;
        if entry_offset < self.machine_range.start_offset || entry_offset >= end_offset {
            return Err(ExecutableMemoryCompartmentError::EntryOffsetOutOfRange {
                entry_offset,
                range: self.machine_range,
            });
        }

        self.validate_mapped_machine_range(MachineCodeRange {
            allocation: self.allocation,
            start_offset: entry_offset,
            size_bytes: 1,
        })
    }

    #[cfg(test)]
    fn bytes_for_testing(
        &self,
        range: MachineCodeRange,
    ) -> Result<Vec<u8>, ExecutableMemoryCompartmentError> {
        if self.lifecycle == ExecutableAllocationLifecycle::Released {
            return Err(ExecutableMemoryCompartmentError::AlreadyReleased);
        }
        self.validate_mapped_machine_range(range)?;

        #[cfg(unix)]
        {
            let mapping = self
                .mapping
                .as_ref()
                .ok_or(ExecutableMemoryCompartmentError::AlreadyReleased)?;
            mapping
                .bytes_for_testing(range.start_offset as usize, range.size_bytes as usize)
                .map_err(map_platform_error)
        }
        #[cfg(not(unix))]
        {
            Err(ExecutableMemoryCompartmentError::UnsupportedPlatform)
        }
    }
}

#[cfg(unix)]
fn platform_page_size() -> Result<ExecutableMemoryPageSize, ExecutableMemoryCompartmentError> {
    unix_executable_memory::page_size()
        .map(ExecutableMemoryPageSize)
        .map_err(map_platform_error)
}

fn mapped_byte_len_for_range(
    range: MachineCodeRange,
    page_size: ExecutableMemoryPageSize,
) -> Result<u32, ExecutableMemoryCompartmentError> {
    range
        .validate()
        .map_err(|error| ExecutableMemoryCompartmentError::RangeInvalid { error })?;
    let end_offset = range
        .end_offset()
        .ok_or(ExecutableMemoryCompartmentError::RangeInvalid {
            error: MachineCodeValidationError::RangeEndOverflow,
        })?;
    let page_size = page_size.0;
    if page_size == 0 || !page_size.is_power_of_two() {
        return Err(ExecutableMemoryCompartmentError::PageSizeInvalid {
            page_size: i64::from(page_size),
        });
    }
    let rounded = end_offset
        .checked_add(page_size - 1)
        .map(|value| value / page_size * page_size)
        .ok_or(ExecutableMemoryCompartmentError::MappedLengthOverflow {
            range,
            page_size: ExecutableMemoryPageSize(page_size),
        })?;
    if rounded == 0 {
        return Err(ExecutableMemoryCompartmentError::MappedLengthOverflow {
            range,
            page_size: ExecutableMemoryPageSize(page_size),
        });
    }
    Ok(rounded)
}

#[cfg(unix)]
fn map_platform_error(
    error: unix_executable_memory::ExecutableMemoryPlatformError,
) -> ExecutableMemoryCompartmentError {
    match error {
        unix_executable_memory::ExecutableMemoryPlatformError::InvalidPageSize { page_size } => {
            ExecutableMemoryCompartmentError::PageSizeInvalid { page_size }
        }
        unix_executable_memory::ExecutableMemoryPlatformError::SystemCall { operation, errno } => {
            ExecutableMemoryCompartmentError::PlatformFailure { operation, errno }
        }
        unix_executable_memory::ExecutableMemoryPlatformError::RangeOutOfBounds => {
            ExecutableMemoryCompartmentError::PlatformFailure {
                operation: ExecutableMemoryPlatformOperation::CopyBytes,
                errno: None,
            }
        }
        unix_executable_memory::ExecutableMemoryPlatformError::AlreadyReleased => {
            ExecutableMemoryCompartmentError::AlreadyReleased
        }
    }
}

#[cfg(all(unix, any(target_arch = "x86_64", target_arch = "aarch64")))]
fn map_call_platform_error(
    error: unix_executable_memory::ExecutableMemoryPlatformError,
    operation: ExecutableMemoryPlatformOperation,
) -> ExecutableMemoryCompartmentError {
    match error {
        unix_executable_memory::ExecutableMemoryPlatformError::RangeOutOfBounds => {
            ExecutableMemoryCompartmentError::PlatformFailure {
                operation,
                errno: None,
            }
        }
        error => map_platform_error(error),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_request(byte_len: u32) -> ExecutableMemoryCompartmentRequest {
        ExecutableMemoryCompartmentRequest::new(
            ExecutableAllocationId(7),
            MachineCodeOwnership::SharedStub,
            byte_len,
        )
    }

    #[cfg(unix)]
    #[test]
    fn allocation_copy_protect_and_release_follow_wx_lifecycle() {
        let bytes = [0x90, 0x90, 0xc3, 0xcc];
        let mut compartment =
            ExecutableMemoryCompartment::allocate(test_request(bytes.len() as u32)).unwrap();

        assert_eq!(
            compartment.protection(),
            ExecutableMemoryProtection::Writable
        );
        assert_eq!(
            compartment.lifecycle(),
            ExecutableAllocationLifecycle::AllocatedWritable
        );
        assert!(compartment.mapped_range().byte_len >= bytes.len() as u32);
        assert!(compartment.mapped_range().byte_len.is_power_of_two());

        compartment
            .copy_from_slice(compartment.machine_range(), &bytes)
            .unwrap();
        assert_eq!(
            compartment
                .bytes_for_testing(compartment.machine_range())
                .unwrap(),
            bytes
        );
        assert_eq!(
            compartment.executable_machine_code_handle(),
            Err(ExecutableMemoryCompartmentError::WrongProtection {
                expected: ExecutableMemoryProtection::Executable,
                actual: ExecutableMemoryProtection::Writable,
            })
        );

        compartment.protect_executable().unwrap();
        assert_eq!(
            compartment.protection(),
            ExecutableMemoryProtection::Executable
        );
        assert_eq!(
            compartment.lifecycle(),
            ExecutableAllocationLifecycle::LinkedExecutable
        );
        assert_eq!(
            compartment
                .bytes_for_testing(compartment.machine_range())
                .unwrap(),
            bytes
        );

        let handle = compartment.executable_machine_code_handle().unwrap();
        assert_eq!(handle.allocation, ExecutableAllocationId(7));
        assert_eq!(handle.range, compartment.machine_range());
        assert_eq!(handle.symbol, None);

        compartment.release().unwrap();
        assert_eq!(
            compartment.protection(),
            ExecutableMemoryProtection::Decommitted
        );
        assert_eq!(
            compartment.lifecycle(),
            ExecutableAllocationLifecycle::Released
        );
        assert_eq!(
            compartment.mutation_authority(),
            ExecutableMutationAuthority::AllocatorOnly
        );
        assert!(matches!(
            compartment.bytes_for_testing(compartment.machine_range()),
            Err(ExecutableMemoryCompartmentError::AlreadyReleased)
        ));
    }

    #[cfg(unix)]
    #[test]
    fn write_after_rx_is_rejected_by_safe_state() {
        let bytes = [0x90, 0xc3];
        let mut compartment =
            ExecutableMemoryCompartment::allocate(test_request(bytes.len() as u32)).unwrap();
        compartment
            .copy_from_slice(compartment.machine_range(), &bytes)
            .unwrap();
        compartment.protect_executable().unwrap();

        assert_eq!(
            compartment.copy_from_slice(compartment.machine_range(), &bytes),
            Err(ExecutableMemoryCompartmentError::WrongProtection {
                expected: ExecutableMemoryProtection::Writable,
                actual: ExecutableMemoryProtection::Executable,
            })
        );
    }

    #[cfg(all(unix, target_arch = "x86_64"))]
    fn opaque_test_ptr() -> NonNull<c_void> {
        NonNull::<u8>::dangling().cast()
    }

    fn non_null_addr(address: usize) -> NonNull<c_void> {
        NonNull::new(address as *mut c_void).expect("non-null test address")
    }

    #[test]
    fn arm64_jsc_stack_call_request_validates_call_frame_relative_entry_sp() {
        let request = ExecutableMemoryArm64JscStackCallRequest::new(
            12,
            non_null_addr(0x2010),
            non_null_addr(0x2000),
        );
        assert_eq!(request.validate(), Ok(()));

        let mismatch = ExecutableMemoryArm64JscStackCallRequest::new(
            12,
            non_null_addr(0x2018),
            non_null_addr(0x2000),
        );
        assert_eq!(
            mismatch.validate(),
            Err(
                ExecutableMemoryArm64JscStackCallRequestValidationError::EntryStackPointerMismatch {
                    expected_entry_sp: 0x2010,
                    actual_entry_sp: 0x2018,
                }
            )
        );

        let unaligned = ExecutableMemoryArm64JscStackCallRequest::new(
            12,
            non_null_addr(0x2018),
            non_null_addr(0x2008),
        );
        assert_eq!(
            unaligned.validate(),
            Err(
                ExecutableMemoryArm64JscStackCallRequestValidationError::CallFrameUnaligned {
                    call_frame: 0x2008,
                }
            )
        );
    }

    #[cfg(all(unix, target_arch = "x86_64"))]
    fn p6_call_request(entry_offset: u32) -> ExecutableMemoryP6CallRequest {
        ExecutableMemoryP6CallRequest::new(
            entry_offset,
            opaque_test_ptr(),
            opaque_test_ptr(),
            0,
            opaque_test_ptr(),
        )
    }

    #[cfg(all(unix, target_arch = "x86_64"))]
    fn p6_call_request_with_callee(
        entry_offset: u32,
        callee_value_bits: u64,
    ) -> ExecutableMemoryP6CallRequest {
        ExecutableMemoryP6CallRequest::new(
            entry_offset,
            opaque_test_ptr(),
            opaque_test_ptr(),
            callee_value_bits,
            opaque_test_ptr(),
        )
    }

    #[cfg(all(unix, target_arch = "x86_64"))]
    fn p9_reentry_request(
        entry_offset: u32,
        result_bits: u64,
    ) -> ExecutableMemoryP9PostCallReentryRequest {
        ExecutableMemoryP9PostCallReentryRequest::new(
            entry_offset,
            opaque_test_ptr(),
            opaque_test_ptr(),
            result_bits,
            opaque_test_ptr(),
            0,
        )
    }

    #[cfg(all(unix, target_arch = "x86_64"))]
    fn p9_reentry_request_with_callee(
        entry_offset: u32,
        result_bits: u64,
        callee_value_bits: u64,
    ) -> ExecutableMemoryP9PostCallReentryRequest {
        ExecutableMemoryP9PostCallReentryRequest::new(
            entry_offset,
            opaque_test_ptr(),
            opaque_test_ptr(),
            result_bits,
            opaque_test_ptr(),
            callee_value_bits,
        )
    }

    #[cfg(all(unix, target_arch = "x86_64"))]
    #[test]
    fn p6_x86_64_call_returns_known_encoded_bits() {
        const EXPECTED: u64 = 0x1122_3344_5566_7788;
        let mut bytes = vec![0x48, 0xb8];
        bytes.extend_from_slice(&EXPECTED.to_le_bytes());
        bytes.push(0xc3);

        let mut compartment =
            ExecutableMemoryCompartment::allocate(test_request(bytes.len() as u32)).unwrap();
        compartment
            .copy_from_slice(compartment.machine_range(), &bytes)
            .unwrap();
        compartment.protect_executable().unwrap();

        assert_eq!(
            compartment
                .call_p6_x86_64_entry(p6_call_request(0))
                .unwrap(),
            ExecutableMemoryP6CallResult {
                encoded_js_value_bits: EXPECTED,
            }
        );
    }

    #[cfg(all(unix, target_arch = "x86_64"))]
    #[test]
    fn p9_x86_64_post_call_reentry_passes_seeded_result_bits_as_third_argument() {
        const EXPECTED: u64 = 0x8877_6655_4433_2211;
        let bytes = [0x48, 0x89, 0xd0, 0xc3];

        let mut compartment =
            ExecutableMemoryCompartment::allocate(test_request(bytes.len() as u32)).unwrap();
        compartment
            .copy_from_slice(compartment.machine_range(), &bytes)
            .unwrap();
        compartment.protect_executable().unwrap();

        assert_eq!(
            compartment
                .call_p9_x86_64_owner_post_call_reentry(p9_reentry_request(0, EXPECTED))
                .unwrap(),
            ExecutableMemoryP6CallResult {
                encoded_js_value_bits: EXPECTED,
            }
        );
    }

    #[cfg(all(unix, target_arch = "x86_64"))]
    #[test]
    fn p6_x86_64_call_passes_callee_bits_as_third_argument() {
        const EXPECTED: u64 = 0x1020_3040_5060_7080;
        let bytes = [0x48, 0x89, 0xd0, 0xc3];

        let mut compartment =
            ExecutableMemoryCompartment::allocate(test_request(bytes.len() as u32)).unwrap();
        compartment
            .copy_from_slice(compartment.machine_range(), &bytes)
            .unwrap();
        compartment.protect_executable().unwrap();

        assert_eq!(
            compartment
                .call_p6_x86_64_entry(p6_call_request_with_callee(0, EXPECTED))
                .unwrap(),
            ExecutableMemoryP6CallResult {
                encoded_js_value_bits: EXPECTED,
            }
        );
    }

    #[cfg(all(unix, target_arch = "x86_64"))]
    #[test]
    fn p9_x86_64_post_call_reentry_passes_callee_bits_as_fifth_argument() {
        const RESULT: u64 = 0x8877_6655_4433_2211;
        const EXPECTED_CALLEE: u64 = 0x1122_3344_5566_7788;
        let bytes = [0x4c, 0x89, 0xc0, 0xc3];

        let mut compartment =
            ExecutableMemoryCompartment::allocate(test_request(bytes.len() as u32)).unwrap();
        compartment
            .copy_from_slice(compartment.machine_range(), &bytes)
            .unwrap();
        compartment.protect_executable().unwrap();

        assert_eq!(
            compartment
                .call_p9_x86_64_owner_post_call_reentry(p9_reentry_request_with_callee(
                    0,
                    RESULT,
                    EXPECTED_CALLEE,
                ))
                .unwrap(),
            ExecutableMemoryP6CallResult {
                encoded_js_value_bits: EXPECTED_CALLEE,
            }
        );
    }

    #[cfg(all(unix, target_arch = "x86_64"))]
    #[test]
    fn p6_x86_64_call_rejects_writable_mapping() {
        let bytes = [0xc3];
        let mut compartment =
            ExecutableMemoryCompartment::allocate(test_request(bytes.len() as u32)).unwrap();
        compartment
            .copy_from_slice(compartment.machine_range(), &bytes)
            .unwrap();

        assert_eq!(
            compartment.call_p6_x86_64_entry(p6_call_request(0)),
            Err(ExecutableMemoryCompartmentError::WrongProtection {
                expected: ExecutableMemoryProtection::Executable,
                actual: ExecutableMemoryProtection::Writable,
            })
        );
    }

    #[cfg(all(unix, target_arch = "x86_64"))]
    #[test]
    fn p6_x86_64_call_rejects_released_mapping() {
        let bytes = [0xc3];
        let mut compartment =
            ExecutableMemoryCompartment::allocate(test_request(bytes.len() as u32)).unwrap();
        compartment
            .copy_from_slice(compartment.machine_range(), &bytes)
            .unwrap();
        compartment.protect_executable().unwrap();
        compartment.release().unwrap();

        assert_eq!(
            compartment.call_p6_x86_64_entry(p6_call_request(0)),
            Err(ExecutableMemoryCompartmentError::AlreadyReleased)
        );
    }

    #[cfg(all(unix, target_arch = "x86_64"))]
    #[test]
    fn p6_x86_64_call_rejects_entry_offset_out_of_range() {
        let bytes = [0xc3];
        let mut compartment =
            ExecutableMemoryCompartment::allocate(test_request(bytes.len() as u32)).unwrap();
        compartment
            .copy_from_slice(compartment.machine_range(), &bytes)
            .unwrap();
        compartment.protect_executable().unwrap();

        assert_eq!(
            compartment.call_p6_x86_64_entry(p6_call_request(bytes.len() as u32)),
            Err(ExecutableMemoryCompartmentError::EntryOffsetOutOfRange {
                entry_offset: bytes.len() as u32,
                range: compartment.machine_range(),
            })
        );
    }

    #[cfg(unix)]
    #[test]
    fn range_validation_rejects_mismatched_or_out_of_bounds_ranges() {
        let bytes = [0x90, 0xc3];
        let mut compartment =
            ExecutableMemoryCompartment::allocate(test_request(bytes.len() as u32)).unwrap();

        let mismatched_allocation = MachineCodeRange {
            allocation: ExecutableAllocationId(8),
            start_offset: 0,
            size_bytes: bytes.len() as u32,
        };
        assert!(matches!(
            compartment.copy_from_slice(mismatched_allocation, &bytes),
            Err(ExecutableMemoryCompartmentError::MappedRangeInvalid {
                reason: ExecutableMemoryResidencyValidationError::MappedRangeAllocationMismatch {
                    expected: ExecutableAllocationId(7),
                    actual: ExecutableAllocationId(8),
                }
            })
        ));

        let out_of_bounds = MachineCodeRange {
            allocation: ExecutableAllocationId(7),
            start_offset: compartment.mapped_range().byte_len - 1,
            size_bytes: 2,
        };
        assert!(matches!(
            compartment.copy_from_slice(out_of_bounds, &bytes),
            Err(ExecutableMemoryCompartmentError::MappedRangeInvalid {
                reason:
                    ExecutableMemoryResidencyValidationError::MappedRangeDoesNotContainMachineRange {
                        ..
                    }
            })
        ));

        let invalid_request = ExecutableMemoryCompartmentRequest::with_range(
            ExecutableAllocationId(7),
            MachineCodeOwnership::SharedStub,
            MachineCodeRange {
                allocation: ExecutableAllocationId(9),
                start_offset: 0,
                size_bytes: 1,
            },
            ExecutableMutationAuthority::LinkBuffer,
        );
        assert!(matches!(
            ExecutableMemoryCompartment::allocate(invalid_request),
            Err(ExecutableMemoryCompartmentError::AllocationLedgerInvalid {
                reason: ExecutableLedgerValidationError::AllocationRangeMismatch {
                    expected: ExecutableAllocationId(7),
                    actual: ExecutableAllocationId(9),
                }
            })
        ));
    }

    #[cfg(unix)]
    #[test]
    fn double_release_and_use_after_release_are_rejected() {
        let bytes = [0x90, 0xc3];
        let mut compartment =
            ExecutableMemoryCompartment::allocate(test_request(bytes.len() as u32)).unwrap();

        compartment
            .copy_from_slice(compartment.machine_range(), &bytes)
            .unwrap();
        compartment.release().unwrap();

        assert_eq!(
            compartment.release(),
            Err(ExecutableMemoryCompartmentError::AlreadyReleased)
        );
        assert_eq!(
            compartment.copy_from_slice(compartment.machine_range(), &bytes),
            Err(ExecutableMemoryCompartmentError::AlreadyReleased)
        );
        assert_eq!(
            compartment.protect_executable(),
            Err(ExecutableMemoryCompartmentError::AlreadyReleased)
        );
    }

    #[cfg(not(unix))]
    #[test]
    fn unsupported_platform_is_structurally_harmless() {
        assert!(matches!(
            ExecutableMemoryCompartment::allocate(test_request(1)),
            Err(ExecutableMemoryCompartmentError::UnsupportedPlatform)
        ));
    }
}
