//! Baseline machine-byte emission provenance.
//!
//! This module records the boundary between baseline-generated bytecode
//! metadata and linked machine-byte images. It is intentionally
//! non-executable: it stores no raw pointers, exposes no function pointers,
//! grants no callable authority, and performs no platform operations. Until a
//! concrete emitter owns construction of the input bytes, this record is byte
//! provenance and ABI-shape evidence, not proof that the bytes are safe to call.

use crate::assembler::{
    AssemblerArchitecture, AssemblerBufferDescriptor, AssemblerBufferId, AssemblerBufferLifecycle,
    AssemblerByteImage, AssemblerByteImageDigest, AssemblerByteImageId, AssemblerDataKind,
    AssemblerValidationError, LinkBufferProfile, LinkBufferState, LinkedAssemblerByteImage,
};
use crate::jit::abi::{EntryAbi, Entrypoint, EntrypointKind, BASELINE_ABI_DESCRIPTOR};
use crate::jit::code::{
    BaselineAbiProof, BaselineEntryArtifact, CodeLiveness, CodeOriginKind, CodeOwnership,
    JitCodeValidationError, JitType,
};
use crate::jit::machine::{
    MachineCodeHandle, MachineCodeOwnership, MachineCodeRange, MachineCodeValidationError,
};
use crate::jit::plan::{
    BaselineBytecodeEligibilityProof, BaselineBytecodeSnapshotFingerprint,
    BaselineGeneratedEffectContract, BaselineSupportedOpcodeSubset,
};
use crate::jit::JitCodeId;
use crate::runtime::{CodeBlockId, NativeCodeId};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BaselineMachineCodeEmitterKind {
    P6Arm64NoCallNoHeapReturnSeedSubset,
    P6X86_64NoCallNoHeapSubset,
    P8aX86_64NoCallNoHeapBranchSubset,
    P8bX86_64NoCallNoHeapBranchTruthinessSubset,
    P6X86_64NoCallNoHeapBitAndOrSubset,
    P8aX86_64NoCallNoHeapBitAndOrBranchSubset,
    P8bX86_64NoCallNoHeapBitAndOrBranchTruthinessSubset,
    P6X86_64NoCallNoHeapBitAndOrEqualitySubset,
    P8aX86_64NoCallNoHeapBitAndOrEqualityBranchSubset,
    P8bX86_64NoCallNoHeapBitAndOrEqualityBranchTruthinessSubset,
    P6X86_64NoCallNoHeapBitAndOrEqualityRelationalSubset,
    P8aX86_64NoCallNoHeapBitAndOrEqualityRelationalBranchSubset,
    P8bX86_64NoCallNoHeapBitAndOrEqualityRelationalBranchTruthinessSubset,
    P6X86_64NoCallNoHeapBitAndOrNoCallLooseEqualitySubset,
    P8aX86_64NoCallNoHeapBitAndOrNoCallLooseEqualityBranchSubset,
    P8bX86_64NoCallNoHeapBitAndOrNoCallLooseEqualityBranchTruthinessSubset,
    P6X86_64NoCallNoHeapBitAndOrNoCallLooseEqualityRelationalSubset,
    P8aX86_64NoCallNoHeapBitAndOrNoCallLooseEqualityRelationalBranchSubset,
    P8bX86_64NoCallNoHeapBitAndOrNoCallLooseEqualityRelationalBranchTruthinessSubset,
    P6X86_64NoCallNoHeapBitAndOrNoCallLooseEqualityRelationalPrimitiveToNumberSubset,
    P8aX86_64NoCallNoHeapBitAndOrNoCallLooseEqualityRelationalPrimitiveToNumberBranchSubset,
    P8bX86_64NoCallNoHeapBitAndOrNoCallLooseEqualityRelationalPrimitiveToNumberBranchTruthinessSubset,
    P6X86_64NoCallNoHeapBitwiseRelationalJumpsPrimitiveTruthinessPrimitiveBooleanSubset,
}

impl BaselineMachineCodeEmitterKind {
    pub const fn expected_architecture(self) -> AssemblerArchitecture {
        match self {
            Self::P6Arm64NoCallNoHeapReturnSeedSubset => AssemblerArchitecture::Arm64,
            Self::P6X86_64NoCallNoHeapSubset
            | Self::P8aX86_64NoCallNoHeapBranchSubset
            | Self::P8bX86_64NoCallNoHeapBranchTruthinessSubset
            | Self::P6X86_64NoCallNoHeapBitAndOrSubset
            | Self::P8aX86_64NoCallNoHeapBitAndOrBranchSubset
            | Self::P8bX86_64NoCallNoHeapBitAndOrBranchTruthinessSubset
            | Self::P6X86_64NoCallNoHeapBitAndOrEqualitySubset
            | Self::P8aX86_64NoCallNoHeapBitAndOrEqualityBranchSubset
            | Self::P8bX86_64NoCallNoHeapBitAndOrEqualityBranchTruthinessSubset
            | Self::P6X86_64NoCallNoHeapBitAndOrEqualityRelationalSubset
            | Self::P8aX86_64NoCallNoHeapBitAndOrEqualityRelationalBranchSubset
            | Self::P8bX86_64NoCallNoHeapBitAndOrEqualityRelationalBranchTruthinessSubset
            | Self::P6X86_64NoCallNoHeapBitAndOrNoCallLooseEqualitySubset
            | Self::P8aX86_64NoCallNoHeapBitAndOrNoCallLooseEqualityBranchSubset
            | Self::P8bX86_64NoCallNoHeapBitAndOrNoCallLooseEqualityBranchTruthinessSubset
            | Self::P6X86_64NoCallNoHeapBitAndOrNoCallLooseEqualityRelationalSubset
            | Self::P8aX86_64NoCallNoHeapBitAndOrNoCallLooseEqualityRelationalBranchSubset
            | Self::P8bX86_64NoCallNoHeapBitAndOrNoCallLooseEqualityRelationalBranchTruthinessSubset
            | Self::P6X86_64NoCallNoHeapBitAndOrNoCallLooseEqualityRelationalPrimitiveToNumberSubset
            | Self::P8aX86_64NoCallNoHeapBitAndOrNoCallLooseEqualityRelationalPrimitiveToNumberBranchSubset
            | Self::P8bX86_64NoCallNoHeapBitAndOrNoCallLooseEqualityRelationalPrimitiveToNumberBranchTruthinessSubset
            | Self::P6X86_64NoCallNoHeapBitwiseRelationalJumpsPrimitiveTruthinessPrimitiveBooleanSubset => {
                AssemblerArchitecture::X86_64
            }
        }
    }

    pub const fn supported_opcode_subset(self) -> BaselineSupportedOpcodeSubset {
        match self {
            Self::P6Arm64NoCallNoHeapReturnSeedSubset => {
                // The ARM64 seed reuses the existing P6 lowering/proof envelope
                // so unsupported arithmetic bodies can fall back through the
                // current generated/x86_64-semantic path. The bytes emitted by
                // this backend are narrower: constants, moves, callee/frame
                // loads, and terminal returns only.
                BaselineSupportedOpcodeSubset::P6ConstantsMovesReturnInt32Arithmetic
            }
            Self::P6X86_64NoCallNoHeapSubset => {
                BaselineSupportedOpcodeSubset::P6ConstantsMovesReturnInt32Arithmetic
            }
            Self::P8aX86_64NoCallNoHeapBranchSubset => {
                BaselineSupportedOpcodeSubset::P8aConstantsMovesReturnInt32ArithmeticBranchNullish
            }
            Self::P8bX86_64NoCallNoHeapBranchTruthinessSubset => {
                BaselineSupportedOpcodeSubset::P8bConstantsMovesReturnInt32ArithmeticBranchNullishFalse
            }
            Self::P6X86_64NoCallNoHeapBitAndOrSubset => {
                BaselineSupportedOpcodeSubset::P6ConstantsMovesReturnInt32ArithmeticBitAndOr
            }
            Self::P8aX86_64NoCallNoHeapBitAndOrBranchSubset => {
                BaselineSupportedOpcodeSubset::P8aConstantsMovesReturnInt32ArithmeticBitAndOrBranchNullish
            }
            Self::P8bX86_64NoCallNoHeapBitAndOrBranchTruthinessSubset => {
                BaselineSupportedOpcodeSubset::P8bConstantsMovesReturnInt32ArithmeticBitAndOrBranchNullishFalse
            }
            Self::P6X86_64NoCallNoHeapBitAndOrEqualitySubset => {
                BaselineSupportedOpcodeSubset::P6ConstantsMovesReturnInt32ArithmeticBitAndOrEquality
            }
            Self::P8aX86_64NoCallNoHeapBitAndOrEqualityBranchSubset => {
                BaselineSupportedOpcodeSubset::P8aConstantsMovesReturnInt32ArithmeticBitAndOrEqualityBranchNullish
            }
            Self::P8bX86_64NoCallNoHeapBitAndOrEqualityBranchTruthinessSubset => {
                BaselineSupportedOpcodeSubset::P8bConstantsMovesReturnInt32ArithmeticBitAndOrEqualityBranchNullishFalse
            }
            Self::P6X86_64NoCallNoHeapBitAndOrEqualityRelationalSubset => {
                BaselineSupportedOpcodeSubset::P6ConstantsMovesReturnInt32ArithmeticBitAndOrEqualityRelational
            }
            Self::P8aX86_64NoCallNoHeapBitAndOrEqualityRelationalBranchSubset => {
                BaselineSupportedOpcodeSubset::P8aConstantsMovesReturnInt32ArithmeticBitAndOrEqualityRelationalBranchNullish
            }
            Self::P8bX86_64NoCallNoHeapBitAndOrEqualityRelationalBranchTruthinessSubset => {
                BaselineSupportedOpcodeSubset::P8bConstantsMovesReturnInt32ArithmeticBitAndOrEqualityRelationalBranchNullishFalse
            }
            Self::P6X86_64NoCallNoHeapBitAndOrNoCallLooseEqualitySubset => {
                BaselineSupportedOpcodeSubset::P6ConstantsMovesReturnInt32ArithmeticBitAndOrNoCallLooseEquality
            }
            Self::P8aX86_64NoCallNoHeapBitAndOrNoCallLooseEqualityBranchSubset => {
                BaselineSupportedOpcodeSubset::P8aConstantsMovesReturnInt32ArithmeticBitAndOrNoCallLooseEqualityBranchNullish
            }
            Self::P8bX86_64NoCallNoHeapBitAndOrNoCallLooseEqualityBranchTruthinessSubset => {
                BaselineSupportedOpcodeSubset::P8bConstantsMovesReturnInt32ArithmeticBitAndOrNoCallLooseEqualityBranchNullishFalse
            }
            Self::P6X86_64NoCallNoHeapBitAndOrNoCallLooseEqualityRelationalSubset => {
                BaselineSupportedOpcodeSubset::P6ConstantsMovesReturnInt32ArithmeticBitAndOrNoCallLooseEqualityRelational
            }
            Self::P8aX86_64NoCallNoHeapBitAndOrNoCallLooseEqualityRelationalBranchSubset => {
                BaselineSupportedOpcodeSubset::P8aConstantsMovesReturnInt32ArithmeticBitAndOrNoCallLooseEqualityRelationalBranchNullish
            }
            Self::P8bX86_64NoCallNoHeapBitAndOrNoCallLooseEqualityRelationalBranchTruthinessSubset => {
                BaselineSupportedOpcodeSubset::P8bConstantsMovesReturnInt32ArithmeticBitAndOrNoCallLooseEqualityRelationalBranchNullishFalse
            }
            Self::P6X86_64NoCallNoHeapBitAndOrNoCallLooseEqualityRelationalPrimitiveToNumberSubset => {
                BaselineSupportedOpcodeSubset::P6ConstantsMovesReturnInt32ArithmeticBitAndOrNoCallLooseEqualityRelationalPrimitiveToNumber
            }
            Self::P8aX86_64NoCallNoHeapBitAndOrNoCallLooseEqualityRelationalPrimitiveToNumberBranchSubset => {
                BaselineSupportedOpcodeSubset::P8aConstantsMovesReturnInt32ArithmeticBitAndOrNoCallLooseEqualityRelationalPrimitiveToNumberBranchNullish
            }
            Self::P8bX86_64NoCallNoHeapBitAndOrNoCallLooseEqualityRelationalPrimitiveToNumberBranchTruthinessSubset => {
                BaselineSupportedOpcodeSubset::P8bConstantsMovesReturnInt32ArithmeticBitAndOrNoCallLooseEqualityRelationalPrimitiveToNumberBranchNullishFalse
            }
            Self::P6X86_64NoCallNoHeapBitwiseRelationalJumpsPrimitiveTruthinessPrimitiveBooleanSubset => {
                BaselineSupportedOpcodeSubset::P6ConstantsMovesReturnInt32ArithmeticBitwiseRelationalJumpsPrimitiveTruthinessPrimitiveBoolean
            }
        }
    }

    pub const fn supported_effect_contract(self) -> BaselineGeneratedEffectContract {
        self.supported_opcode_subset().generated_effect_contract()
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BaselineMachineCodeEmissionRequest<'a> {
    pub emitter_kind: BaselineMachineCodeEmitterKind,
    pub entry_artifact: &'a BaselineEntryArtifact,
    pub eligibility_proof: &'a BaselineBytecodeEligibilityProof,
    pub source_buffer: &'a AssemblerBufferDescriptor,
    pub source_image: &'a AssemblerByteImage,
    pub linked_image: Option<&'a LinkedAssemblerByteImage>,
    /// Allocation-relative offset for the entry instruction. This is metadata,
    /// not an address and not a callable function pointer.
    pub entry_offset: u32,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum BaselineMachineCodeEmissionValidationError {
    ArtifactInvalid {
        error: JitCodeValidationError,
    },
    CodeIdZero,
    NativeCodeIdZero,
    UnsupportedOpcodeSubset {
        emitter: BaselineMachineCodeEmitterKind,
        expected: BaselineSupportedOpcodeSubset,
        actual: BaselineSupportedOpcodeSubset,
    },
    UnsupportedEffectContract {
        emitter: BaselineMachineCodeEmitterKind,
        expected: BaselineGeneratedEffectContract,
        actual: BaselineGeneratedEffectContract,
    },
    BaselineAbiProofMismatch,
    EligibilityOwnerMismatch {
        expected: CodeBlockId,
        actual: CodeBlockId,
    },
    SourceBufferInvalid {
        error: AssemblerValidationError,
    },
    SourceBufferNotFrozen {
        actual: AssemblerBufferLifecycle,
    },
    SourceBufferDataKindMismatch {
        expected: AssemblerDataKind,
        actual: AssemblerDataKind,
    },
    SourceArchitectureMismatch {
        expected: AssemblerArchitecture,
        actual: Option<AssemblerArchitecture>,
    },
    SourceImageInvalid {
        error: AssemblerValidationError,
    },
    RelocationsUnsupported {
        source: BaselineMachineCodeEmissionRelocationSource,
        actual: usize,
    },
    LinkedImageMissing,
    LinkedImageInvalid {
        error: AssemblerValidationError,
    },
    LinkedImageSourceMismatch {
        expected: AssemblerByteImageId,
        actual: AssemblerByteImageId,
    },
    LinkedImageSourceDigestMismatch {
        expected: AssemblerByteImageDigest,
        actual: AssemblerByteImageDigest,
    },
    LinkedImageOutputDigestMismatch {
        expected: AssemblerByteImageDigest,
        actual: AssemblerByteImageDigest,
    },
    LinkedImageOutputSizeMismatch {
        expected: u32,
        actual: u32,
    },
    LinkedImageProfileMismatch {
        expected: LinkBufferProfile,
        actual: LinkBufferProfile,
    },
    LinkedImageStateMismatch {
        expected: LinkBufferState,
        actual: LinkBufferState,
    },
    MachineCodeInvalid {
        error: MachineCodeValidationError,
    },
    MachineCodeOwnerMismatch {
        expected: MachineCodeOwnership,
        actual: MachineCodeOwnership,
    },
    MachineCodeNativeSymbolMismatch {
        expected: NativeCodeId,
        actual: Option<NativeCodeId>,
    },
    MachineCodeRangeMismatch {
        expected: MachineCodeRange,
        actual: MachineCodeRange,
    },
    MachineCodeRangeSizeMismatch {
        expected: u32,
        actual: u32,
    },
    EntrypointMismatch {
        expected_code: JitCodeId,
        actual: Entrypoint,
    },
    EntryOffsetOutOfRange {
        entry_offset: u32,
        range: MachineCodeRange,
    },
    ProofMismatch,
    SealMismatch,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BaselineMachineCodeEmissionRelocationSource {
    SourceBuffer,
    SourceImage,
    LinkedImage,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BaselineMachineCodeEmissionRecord {
    pub emitter_kind: BaselineMachineCodeEmitterKind,
    pub owner: CodeBlockId,
    pub code_id: JitCodeId,
    pub native_code: NativeCodeId,
    pub machine_code: MachineCodeHandle,
    pub machine_range: MachineCodeRange,
    pub entrypoint: Entrypoint,
    pub supported_opcode_subset: BaselineSupportedOpcodeSubset,
    pub effect_contract: BaselineGeneratedEffectContract,
    pub(crate) bytecode_snapshot: BaselineBytecodeSnapshotFingerprint,
    pub source_buffer: AssemblerBufferId,
    pub source_architecture: AssemblerArchitecture,
    pub source_image: AssemblerByteImageId,
    pub source_digest: AssemblerByteImageDigest,
    pub source_size_bytes: u32,
    pub linked_digest: AssemblerByteImageDigest,
    pub linked_size_bytes: u32,
    pub linked_profile: LinkBufferProfile,
    pub linked_state: LinkBufferState,
    pub relocation_count: usize,
    pub entry_offset: u32,
    baseline_abi_proof: BaselineAbiProof,
    proof: BaselineMachineCodeEmissionProof,
    seal: BaselineMachineCodeEmissionSeal,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct BaselineMachineCodeEmissionProof {
    emitter_kind: BaselineMachineCodeEmitterKind,
    owner: CodeBlockId,
    code_id: JitCodeId,
    native_code: NativeCodeId,
    machine_code: MachineCodeHandle,
    machine_range: MachineCodeRange,
    entrypoint: Entrypoint,
    supported_opcode_subset: BaselineSupportedOpcodeSubset,
    effect_contract: BaselineGeneratedEffectContract,
    bytecode_snapshot: BaselineBytecodeSnapshotFingerprint,
    source_buffer: AssemblerBufferId,
    source_architecture: AssemblerArchitecture,
    source_image: AssemblerByteImageId,
    source_digest: AssemblerByteImageDigest,
    source_size_bytes: u32,
    linked_digest: AssemblerByteImageDigest,
    linked_size_bytes: u32,
    linked_profile: LinkBufferProfile,
    linked_state: LinkBufferState,
    relocation_count: usize,
    entry_offset: u32,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct BaselineMachineCodeEmissionSeal {
    owner: CodeBlockId,
    code_id: JitCodeId,
    native_code: NativeCodeId,
    machine_code: MachineCodeHandle,
    entrypoint: Entrypoint,
    entry_offset: u32,
}

pub fn record_baseline_machine_code_emission(
    request: BaselineMachineCodeEmissionRequest<'_>,
) -> Result<BaselineMachineCodeEmissionRecord, BaselineMachineCodeEmissionValidationError> {
    validate_entry_artifact(
        request.emitter_kind,
        request.entry_artifact,
        request.eligibility_proof,
    )?;
    validate_source_image(
        request.emitter_kind,
        request.source_buffer,
        request.source_image,
    )?;
    let linked_image = request
        .linked_image
        .ok_or(BaselineMachineCodeEmissionValidationError::LinkedImageMissing)?;
    validate_linked_image(request.source_image, linked_image)?;
    validate_machine_code(
        request.entry_artifact.owner,
        request.entry_artifact.native_code,
        request.entry_artifact.machine_code,
        request.entry_artifact.machine_code.range,
        linked_image.output_size_bytes,
    )?;
    validate_entrypoint(request.entry_artifact.id, request.entry_artifact.entrypoint)?;
    validate_entry_offset(
        request.entry_offset,
        request.entry_artifact.machine_code.range,
    )?;

    let record = BaselineMachineCodeEmissionRecord {
        emitter_kind: request.emitter_kind,
        owner: request.entry_artifact.owner,
        code_id: request.entry_artifact.id,
        native_code: request.entry_artifact.native_code,
        machine_code: request.entry_artifact.machine_code,
        machine_range: request.entry_artifact.machine_code.range,
        entrypoint: request.entry_artifact.entrypoint,
        supported_opcode_subset: request.eligibility_proof.opcode_subset(),
        effect_contract: request.eligibility_proof.generated_effect_contract(),
        bytecode_snapshot: request.eligibility_proof.bytecode_snapshot_fingerprint(),
        source_buffer: request.source_buffer.id,
        source_architecture: request.emitter_kind.expected_architecture(),
        source_image: request.source_image.id(),
        source_digest: request.source_image.digest(),
        source_size_bytes: request.source_image.byte_len(),
        linked_digest: linked_image.output_digest,
        linked_size_bytes: linked_image.output_size_bytes,
        linked_profile: linked_image.profile,
        linked_state: linked_image.state,
        relocation_count: linked_image.relocation_count,
        entry_offset: request.entry_offset,
        baseline_abi_proof: request.entry_artifact.baseline_abi_proof,
        proof: BaselineMachineCodeEmissionProof {
            emitter_kind: request.emitter_kind,
            owner: request.entry_artifact.owner,
            code_id: request.entry_artifact.id,
            native_code: request.entry_artifact.native_code,
            machine_code: request.entry_artifact.machine_code,
            machine_range: request.entry_artifact.machine_code.range,
            entrypoint: request.entry_artifact.entrypoint,
            supported_opcode_subset: request.eligibility_proof.opcode_subset(),
            effect_contract: request.eligibility_proof.generated_effect_contract(),
            bytecode_snapshot: request.eligibility_proof.bytecode_snapshot_fingerprint(),
            source_buffer: request.source_buffer.id,
            source_architecture: request.emitter_kind.expected_architecture(),
            source_image: request.source_image.id(),
            source_digest: request.source_image.digest(),
            source_size_bytes: request.source_image.byte_len(),
            linked_digest: linked_image.output_digest,
            linked_size_bytes: linked_image.output_size_bytes,
            linked_profile: linked_image.profile,
            linked_state: linked_image.state,
            relocation_count: linked_image.relocation_count,
            entry_offset: request.entry_offset,
        },
        seal: BaselineMachineCodeEmissionSeal {
            owner: request.entry_artifact.owner,
            code_id: request.entry_artifact.id,
            native_code: request.entry_artifact.native_code,
            machine_code: request.entry_artifact.machine_code,
            entrypoint: request.entry_artifact.entrypoint,
            entry_offset: request.entry_offset,
        },
    };
    record.validate()?;
    Ok(record)
}

impl BaselineMachineCodeEmissionRecord {
    pub fn validate(&self) -> Result<(), BaselineMachineCodeEmissionValidationError> {
        if self.proof != self.expected_proof() {
            return Err(BaselineMachineCodeEmissionValidationError::ProofMismatch);
        }
        if self.seal != self.expected_seal() {
            return Err(BaselineMachineCodeEmissionValidationError::SealMismatch);
        }
        if !self.has_valid_baseline_abi_proof() {
            return Err(BaselineMachineCodeEmissionValidationError::BaselineAbiProofMismatch);
        }
        validate_emitter_subset_and_effect_contract(
            self.emitter_kind,
            self.supported_opcode_subset,
            self.effect_contract,
        )?;
        validate_machine_code(
            self.owner,
            self.native_code,
            self.machine_code,
            self.machine_range,
            self.linked_size_bytes,
        )?;
        validate_entrypoint(self.code_id, self.entrypoint)?;
        validate_entry_offset(self.entry_offset, self.machine_range)?;
        if self.linked_profile != LinkBufferProfile::Baseline {
            return Err(
                BaselineMachineCodeEmissionValidationError::LinkedImageProfileMismatch {
                    expected: LinkBufferProfile::Baseline,
                    actual: self.linked_profile,
                },
            );
        }
        if self.linked_state != LinkBufferState::Linked {
            return Err(
                BaselineMachineCodeEmissionValidationError::LinkedImageStateMismatch {
                    expected: LinkBufferState::Linked,
                    actual: self.linked_state,
                },
            );
        }
        if self.relocation_count != 0 {
            return Err(
                BaselineMachineCodeEmissionValidationError::RelocationsUnsupported {
                    source: BaselineMachineCodeEmissionRelocationSource::LinkedImage,
                    actual: self.relocation_count,
                },
            );
        }
        if self.source_digest != self.linked_digest {
            return Err(
                BaselineMachineCodeEmissionValidationError::LinkedImageOutputDigestMismatch {
                    expected: self.source_digest,
                    actual: self.linked_digest,
                },
            );
        }
        if self.source_size_bytes != self.linked_size_bytes {
            return Err(
                BaselineMachineCodeEmissionValidationError::LinkedImageOutputSizeMismatch {
                    expected: self.source_size_bytes,
                    actual: self.linked_size_bytes,
                },
            );
        }

        Ok(())
    }

    pub fn has_valid_baseline_abi_proof(&self) -> bool {
        self.baseline_abi_proof
            .proves_descriptor(&BASELINE_ABI_DESCRIPTOR)
    }

    fn expected_proof(&self) -> BaselineMachineCodeEmissionProof {
        BaselineMachineCodeEmissionProof {
            emitter_kind: self.emitter_kind,
            owner: self.owner,
            code_id: self.code_id,
            native_code: self.native_code,
            machine_code: self.machine_code,
            machine_range: self.machine_range,
            entrypoint: self.entrypoint,
            supported_opcode_subset: self.supported_opcode_subset,
            effect_contract: self.effect_contract,
            bytecode_snapshot: self.bytecode_snapshot,
            source_buffer: self.source_buffer,
            source_architecture: self.source_architecture,
            source_image: self.source_image,
            source_digest: self.source_digest,
            source_size_bytes: self.source_size_bytes,
            linked_digest: self.linked_digest,
            linked_size_bytes: self.linked_size_bytes,
            linked_profile: self.linked_profile,
            linked_state: self.linked_state,
            relocation_count: self.relocation_count,
            entry_offset: self.entry_offset,
        }
    }

    fn expected_seal(&self) -> BaselineMachineCodeEmissionSeal {
        BaselineMachineCodeEmissionSeal {
            owner: self.owner,
            code_id: self.code_id,
            native_code: self.native_code,
            machine_code: self.machine_code,
            entrypoint: self.entrypoint,
            entry_offset: self.entry_offset,
        }
    }
}

fn validate_entry_artifact(
    emitter: BaselineMachineCodeEmitterKind,
    entry_artifact: &BaselineEntryArtifact,
    eligibility_proof: &BaselineBytecodeEligibilityProof,
) -> Result<(), BaselineMachineCodeEmissionValidationError> {
    if entry_artifact.tier != JitType::Baseline {
        return Err(
            BaselineMachineCodeEmissionValidationError::ArtifactInvalid {
                error: JitCodeValidationError::BaselineEntryTierMismatch,
            },
        );
    }
    if entry_artifact.origin.kind != CodeOriginKind::BaselineCodeBlock {
        return Err(
            BaselineMachineCodeEmissionValidationError::ArtifactInvalid {
                error: JitCodeValidationError::BaselineEntryOriginMismatch,
            },
        );
    }
    match entry_artifact.origin.owner {
        Some(origin_owner) if origin_owner == entry_artifact.owner => {}
        Some(_) => {
            return Err(
                BaselineMachineCodeEmissionValidationError::ArtifactInvalid {
                    error: JitCodeValidationError::BaselineEntryOwnerMismatch,
                },
            );
        }
        None => {
            return Err(
                BaselineMachineCodeEmissionValidationError::ArtifactInvalid {
                    error: JitCodeValidationError::BaselineEntryOwnerMissing,
                },
            );
        }
    }
    if entry_artifact.ownership != CodeOwnership::CodeBlockOwned {
        return Err(
            BaselineMachineCodeEmissionValidationError::ArtifactInvalid {
                error: JitCodeValidationError::BaselineEntryOwnershipMismatch,
            },
        );
    }
    if entry_artifact.liveness != CodeLiveness::Live {
        return Err(
            BaselineMachineCodeEmissionValidationError::ArtifactInvalid {
                error: JitCodeValidationError::BaselineEntryNotLive,
            },
        );
    }
    if entry_artifact.id.0 == 0 {
        return Err(BaselineMachineCodeEmissionValidationError::CodeIdZero);
    }
    if entry_artifact.entrypoint.kind != EntrypointKind::GeneratedCode
        || entry_artifact.entrypoint.abi != EntryAbi::GeneratedCode
        || entry_artifact.entrypoint.code != Some(entry_artifact.id)
    {
        return Err(
            BaselineMachineCodeEmissionValidationError::ArtifactInvalid {
                error: JitCodeValidationError::BaselineEntryEntrypointMissing,
            },
        );
    }
    if eligibility_proof.owner() != entry_artifact.owner {
        return Err(
            BaselineMachineCodeEmissionValidationError::EligibilityOwnerMismatch {
                expected: entry_artifact.owner,
                actual: eligibility_proof.owner(),
            },
        );
    }
    if !entry_artifact
        .baseline_abi_proof
        .proves_descriptor(&BASELINE_ABI_DESCRIPTOR)
    {
        return Err(BaselineMachineCodeEmissionValidationError::BaselineAbiProofMismatch);
    }
    validate_emitter_subset_and_effect_contract(
        emitter,
        eligibility_proof.opcode_subset(),
        eligibility_proof.generated_effect_contract(),
    )
}

fn validate_emitter_subset_and_effect_contract(
    emitter: BaselineMachineCodeEmitterKind,
    subset: BaselineSupportedOpcodeSubset,
    effect_contract: BaselineGeneratedEffectContract,
) -> Result<(), BaselineMachineCodeEmissionValidationError> {
    let expected_subset = emitter.supported_opcode_subset();
    if subset != expected_subset {
        return Err(
            BaselineMachineCodeEmissionValidationError::UnsupportedOpcodeSubset {
                emitter,
                expected: expected_subset,
                actual: subset,
            },
        );
    }

    let expected_effect_contract = emitter.supported_effect_contract();
    if effect_contract != expected_effect_contract
        || effect_contract.opcode_subset != subset
        || !effect_contract.permits_no_heap_allocation_no_runtime_call()
        || effect_contract.summary.may_throw
        || effect_contract.summary.writes_heap
        || effect_contract.touches_gc_roots
    {
        return Err(
            BaselineMachineCodeEmissionValidationError::UnsupportedEffectContract {
                emitter,
                expected: expected_effect_contract,
                actual: effect_contract,
            },
        );
    }

    Ok(())
}

fn validate_source_image(
    emitter: BaselineMachineCodeEmitterKind,
    source_buffer: &AssemblerBufferDescriptor,
    source_image: &AssemblerByteImage,
) -> Result<(), BaselineMachineCodeEmissionValidationError> {
    source_buffer.validate().map_err(|error| {
        BaselineMachineCodeEmissionValidationError::SourceBufferInvalid { error }
    })?;
    if source_buffer.lifecycle != AssemblerBufferLifecycle::FrozenForLink {
        return Err(
            BaselineMachineCodeEmissionValidationError::SourceBufferNotFrozen {
                actual: source_buffer.lifecycle,
            },
        );
    }
    if source_buffer.data_kind != AssemblerDataKind::Code {
        return Err(
            BaselineMachineCodeEmissionValidationError::SourceBufferDataKindMismatch {
                expected: AssemblerDataKind::Code,
                actual: source_buffer.data_kind,
            },
        );
    }
    let expected_architecture = emitter.expected_architecture();
    if source_buffer.architecture != Some(expected_architecture) {
        return Err(
            BaselineMachineCodeEmissionValidationError::SourceArchitectureMismatch {
                expected: expected_architecture,
                actual: source_buffer.architecture,
            },
        );
    }
    if !source_buffer.relocations.is_empty() {
        return Err(
            BaselineMachineCodeEmissionValidationError::RelocationsUnsupported {
                source: BaselineMachineCodeEmissionRelocationSource::SourceBuffer,
                actual: source_buffer.relocations.len(),
            },
        );
    }
    source_image
        .validate_against_source(source_buffer)
        .map_err(
            |error| BaselineMachineCodeEmissionValidationError::SourceImageInvalid { error },
        )?;
    if source_image.descriptor().relocation_count != 0 {
        return Err(
            BaselineMachineCodeEmissionValidationError::RelocationsUnsupported {
                source: BaselineMachineCodeEmissionRelocationSource::SourceImage,
                actual: source_image.descriptor().relocation_count,
            },
        );
    }

    Ok(())
}

fn validate_linked_image(
    source_image: &AssemblerByteImage,
    linked_image: &LinkedAssemblerByteImage,
) -> Result<(), BaselineMachineCodeEmissionValidationError> {
    if linked_image.profile != LinkBufferProfile::Baseline {
        return Err(
            BaselineMachineCodeEmissionValidationError::LinkedImageProfileMismatch {
                expected: LinkBufferProfile::Baseline,
                actual: linked_image.profile,
            },
        );
    }
    if linked_image.state != LinkBufferState::Linked {
        return Err(
            BaselineMachineCodeEmissionValidationError::LinkedImageStateMismatch {
                expected: LinkBufferState::Linked,
                actual: linked_image.state,
            },
        );
    }
    linked_image.validate().map_err(|error| {
        BaselineMachineCodeEmissionValidationError::LinkedImageInvalid { error }
    })?;
    if linked_image.source_image_id != source_image.id() {
        return Err(
            BaselineMachineCodeEmissionValidationError::LinkedImageSourceMismatch {
                expected: source_image.id(),
                actual: linked_image.source_image_id,
            },
        );
    }
    if linked_image.source_image_digest != source_image.digest() {
        return Err(
            BaselineMachineCodeEmissionValidationError::LinkedImageSourceDigestMismatch {
                expected: source_image.digest(),
                actual: linked_image.source_image_digest,
            },
        );
    }
    if linked_image.output_digest != source_image.digest() {
        return Err(
            BaselineMachineCodeEmissionValidationError::LinkedImageOutputDigestMismatch {
                expected: source_image.digest(),
                actual: linked_image.output_digest,
            },
        );
    }
    if linked_image.output_size_bytes != source_image.byte_len() {
        return Err(
            BaselineMachineCodeEmissionValidationError::LinkedImageOutputSizeMismatch {
                expected: source_image.byte_len(),
                actual: linked_image.output_size_bytes,
            },
        );
    }
    if linked_image.relocation_count != 0 {
        return Err(
            BaselineMachineCodeEmissionValidationError::RelocationsUnsupported {
                source: BaselineMachineCodeEmissionRelocationSource::LinkedImage,
                actual: linked_image.relocation_count,
            },
        );
    }

    Ok(())
}

fn validate_machine_code(
    owner: CodeBlockId,
    native_code: NativeCodeId,
    machine_code: MachineCodeHandle,
    machine_range: MachineCodeRange,
    linked_size_bytes: u32,
) -> Result<(), BaselineMachineCodeEmissionValidationError> {
    if native_code == NativeCodeId::default() {
        return Err(BaselineMachineCodeEmissionValidationError::NativeCodeIdZero);
    }
    machine_code.validate().map_err(|error| {
        BaselineMachineCodeEmissionValidationError::MachineCodeInvalid { error }
    })?;
    let expected_owner = MachineCodeOwnership::CodeBlock(owner);
    if machine_code.owner != expected_owner {
        return Err(
            BaselineMachineCodeEmissionValidationError::MachineCodeOwnerMismatch {
                expected: expected_owner,
                actual: machine_code.owner,
            },
        );
    }
    if machine_code.symbol != Some(native_code) {
        return Err(
            BaselineMachineCodeEmissionValidationError::MachineCodeNativeSymbolMismatch {
                expected: native_code,
                actual: machine_code.symbol,
            },
        );
    }
    if machine_code.range != machine_range {
        return Err(
            BaselineMachineCodeEmissionValidationError::MachineCodeRangeMismatch {
                expected: machine_range,
                actual: machine_code.range,
            },
        );
    }
    if machine_range.size_bytes != linked_size_bytes {
        return Err(
            BaselineMachineCodeEmissionValidationError::MachineCodeRangeSizeMismatch {
                expected: linked_size_bytes,
                actual: machine_range.size_bytes,
            },
        );
    }

    Ok(())
}

fn validate_entrypoint(
    code_id: JitCodeId,
    entrypoint: Entrypoint,
) -> Result<(), BaselineMachineCodeEmissionValidationError> {
    if entrypoint.kind != EntrypointKind::GeneratedCode
        || entrypoint.abi != EntryAbi::GeneratedCode
        || entrypoint.code != Some(code_id)
    {
        return Err(
            BaselineMachineCodeEmissionValidationError::EntrypointMismatch {
                expected_code: code_id,
                actual: entrypoint,
            },
        );
    }

    Ok(())
}

fn validate_entry_offset(
    entry_offset: u32,
    machine_range: MachineCodeRange,
) -> Result<(), BaselineMachineCodeEmissionValidationError> {
    let Some(end_offset) = machine_range.end_offset() else {
        return Err(
            BaselineMachineCodeEmissionValidationError::MachineCodeInvalid {
                error: MachineCodeValidationError::RangeEndOverflow,
            },
        );
    };
    if entry_offset < machine_range.start_offset || entry_offset >= end_offset {
        return Err(
            BaselineMachineCodeEmissionValidationError::EntryOffsetOutOfRange {
                entry_offset,
                range: machine_range,
            },
        );
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::assembler::{
        freeze_assembler_byte_image, link_assembler_byte_image, plan_link_buffer_layout,
        AssemblerBufferBuilder, AssemblerByteImageId, AssemblerLabel, AssemblerRelocation,
        AssemblerRelocationKind,
    };
    use crate::bytecode::{BytecodeIndex, CoreOpcode};
    use crate::gc::CellId;
    use crate::jit::{
        BaselineBytecodeEligibilityRecord, BaselineBytecodeInstruction, BaselineBytecodeRange,
        BaselineExceptionMetadataPresence, BaselineRootMapRequirements, CodeFinalizationAuthority,
        CodeLiveness, CodeOrigin, CodeOriginKind, CodeOwnership, ExecutableAllocationId,
        ExecutableAllocationLifecycle, ExecutableMemoryProtection, ExecutableMutationAuthority,
        JitCodeArtifact, JitType, TierCounters, TieringSnapshot, TieringTrigger,
    };

    const CALLER_SUPPLIED_RECORD_BYTES: &[u8] = &[0x31, 0xc0, 0x90, 0x90, 0x90, 0xc3];

    fn owner() -> CodeBlockId {
        CodeBlockId(CellId(1))
    }

    fn native_code() -> NativeCodeId {
        NativeCodeId(11)
    }

    fn code_id() -> JitCodeId {
        JitCodeId(7)
    }

    fn frozen_buffer(architecture: AssemblerArchitecture) -> AssemblerBufferDescriptor {
        AssemblerBufferBuilder::new(crate::assembler::AssemblerBufferId(3))
            .architecture(architecture)
            .lifecycle(AssemblerBufferLifecycle::FrozenForLink)
            .capacity(
                CALLER_SUPPLIED_RECORD_BYTES.len() as u32,
                CALLER_SUPPLIED_RECORD_BYTES.len() as u32,
            )
            .build()
            .unwrap()
    }

    fn frozen_buffer_with_relocation() -> AssemblerBufferDescriptor {
        AssemblerBufferBuilder::new(crate::assembler::AssemblerBufferId(3))
            .architecture(AssemblerArchitecture::X86_64)
            .lifecycle(AssemblerBufferLifecycle::FrozenForLink)
            .capacity(
                CALLER_SUPPLIED_RECORD_BYTES.len() as u32,
                CALLER_SUPPLIED_RECORD_BYTES.len() as u32,
            )
            .label(AssemblerLabel(1))
            .relocation(AssemblerRelocation {
                kind: AssemblerRelocationKind::Jump,
                at_offset: 1,
                target: Some(AssemblerLabel(1)),
            })
            .build()
            .unwrap()
    }

    fn source_image(buffer: &AssemblerBufferDescriptor) -> AssemblerByteImage {
        freeze_assembler_byte_image(
            buffer,
            AssemblerByteImageId(5),
            CALLER_SUPPLIED_RECORD_BYTES.to_vec(),
        )
        .unwrap()
    }

    fn linked_image(
        buffer: &AssemblerBufferDescriptor,
        image: &AssemblerByteImage,
    ) -> LinkedAssemblerByteImage {
        let layout = plan_link_buffer_layout(buffer, LinkBufferProfile::Baseline, None).unwrap();
        link_assembler_byte_image(image, &layout).unwrap()
    }

    fn eligibility_proof(
        subset: BaselineSupportedOpcodeSubset,
    ) -> crate::jit::BaselineBytecodeEligibilityProof {
        eligibility_proof_with_instructions(
            subset,
            vec![
                BaselineBytecodeInstruction {
                    bytecode_index: BytecodeIndex::from_offset(0),
                    opcode: CoreOpcode::LoadInt32,
                },
                BaselineBytecodeInstruction {
                    bytecode_index: BytecodeIndex::from_offset(1),
                    opcode: CoreOpcode::Return,
                },
            ],
        )
    }

    fn eligibility_proof_with_instructions(
        subset: BaselineSupportedOpcodeSubset,
        instructions: Vec<BaselineBytecodeInstruction>,
    ) -> crate::jit::BaselineBytecodeEligibilityProof {
        let start = instructions
            .first()
            .map(|instruction| instruction.bytecode_index)
            .unwrap_or_else(|| BytecodeIndex::from_offset(0));
        let end = instructions
            .last()
            .map(|instruction| instruction.bytecode_index)
            .unwrap_or(start);
        let instruction_count = instructions.len() as u32;
        BaselineBytecodeEligibilityRecord {
            owner: Some(owner()),
            snapshot: TieringSnapshot {
                owner: owner(),
                from_tier: JitType::None,
                to_tier: JitType::Baseline,
                trigger: TieringTrigger::EntryCounter,
                counters: TierCounters::default(),
                osr_entry_bytecode_index: None,
                epoch: 1,
            },
            bytecode: BaselineBytecodeRange {
                start,
                end,
                instruction_count,
            },
            opcode_subset: subset,
            instructions,
            root_map_requirements: BaselineRootMapRequirements::default(),
            exception_metadata: BaselineExceptionMetadataPresence::Present { handler_count: 0 },
        }
        .validate()
        .unwrap()
    }

    fn entry_artifact() -> BaselineEntryArtifact {
        native_artifact()
            .validate_baseline_entry_artifact(owner())
            .unwrap()
    }

    fn proof() -> crate::jit::BaselineBytecodeEligibilityProof {
        eligibility_proof(BaselineSupportedOpcodeSubset::P6ConstantsMovesReturnInt32Arithmetic)
    }

    fn proof_for_subset(
        subset: BaselineSupportedOpcodeSubset,
    ) -> crate::jit::BaselineBytecodeEligibilityProof {
        eligibility_proof(subset)
    }

    fn machine_code() -> MachineCodeHandle {
        let allocation = ExecutableAllocationId(13);
        MachineCodeHandle {
            allocation,
            owner: MachineCodeOwnership::CodeBlock(owner()),
            range: MachineCodeRange {
                allocation,
                start_offset: 0,
                size_bytes: CALLER_SUPPLIED_RECORD_BYTES.len() as u32,
            },
            symbol: Some(native_code()),
            protection: ExecutableMemoryProtection::Executable,
            lifecycle: ExecutableAllocationLifecycle::LinkedExecutable,
            mutation_authority: ExecutableMutationAuthority::LinkBuffer,
        }
    }

    fn entrypoint() -> Entrypoint {
        Entrypoint {
            kind: EntrypointKind::GeneratedCode,
            abi: EntryAbi::GeneratedCode,
            code: Some(code_id()),
            boundary: None,
        }
    }

    fn native_artifact() -> JitCodeArtifact {
        JitCodeArtifact {
            id: code_id(),
            tier: JitType::Baseline,
            origin: CodeOrigin {
                kind: CodeOriginKind::BaselineCodeBlock,
                owner: Some(owner()),
                executable: None,
                bytecode_index: Some(0),
            },
            ownership: CodeOwnership::CodeBlockOwned,
            native_code: Some(native_code()),
            machine_code: Some(machine_code()),
            entrypoint: entrypoint(),
            patchpoints: Vec::new(),
            dependencies: Vec::new(),
            byproducts: Vec::new(),
            disassembly: None,
            liveness: CodeLiveness::Live,
            finalization_authority: CodeFinalizationAuthority::CompilerThread,
        }
    }

    #[allow(clippy::type_complexity)]
    fn accepted_parts() -> (
        BaselineEntryArtifact,
        crate::jit::BaselineBytecodeEligibilityProof,
        AssemblerBufferDescriptor,
        AssemblerByteImage,
        LinkedAssemblerByteImage,
    ) {
        let buffer = frozen_buffer(AssemblerArchitecture::X86_64);
        let image = source_image(&buffer);
        let linked = linked_image(&buffer, &image);
        (entry_artifact(), proof(), buffer, image, linked)
    }

    fn request<'a>(
        entry_artifact: &'a BaselineEntryArtifact,
        eligibility_proof: &'a crate::jit::BaselineBytecodeEligibilityProof,
        buffer: &'a AssemblerBufferDescriptor,
        image: &'a AssemblerByteImage,
        linked: Option<&'a LinkedAssemblerByteImage>,
    ) -> BaselineMachineCodeEmissionRequest<'a> {
        request_with_emitter(
            BaselineMachineCodeEmitterKind::P6X86_64NoCallNoHeapSubset,
            entry_artifact,
            eligibility_proof,
            buffer,
            image,
            linked,
        )
    }

    fn request_with_emitter<'a>(
        emitter_kind: BaselineMachineCodeEmitterKind,
        entry_artifact: &'a BaselineEntryArtifact,
        eligibility_proof: &'a crate::jit::BaselineBytecodeEligibilityProof,
        buffer: &'a AssemblerBufferDescriptor,
        image: &'a AssemblerByteImage,
        linked: Option<&'a LinkedAssemblerByteImage>,
    ) -> BaselineMachineCodeEmissionRequest<'a> {
        BaselineMachineCodeEmissionRequest {
            emitter_kind,
            entry_artifact,
            eligibility_proof,
            source_buffer: buffer,
            source_image: image,
            linked_image: linked,
            entry_offset: entry_artifact.machine_code.range.start_offset,
        }
    }

    #[test]
    fn accepted_record_validates_baseline_emission_byte_shape() {
        let (entry_artifact, proof, buffer, image, linked) = accepted_parts();

        let record = record_baseline_machine_code_emission(request(
            &entry_artifact,
            &proof,
            &buffer,
            &image,
            Some(&linked),
        ))
        .unwrap();

        assert_eq!(
            record.emitter_kind,
            BaselineMachineCodeEmitterKind::P6X86_64NoCallNoHeapSubset
        );
        assert_eq!(record.owner, owner());
        assert_eq!(record.code_id, code_id());
        assert_eq!(record.native_code, native_code());
        assert_eq!(record.machine_code, entry_artifact.machine_code);
        assert_eq!(record.machine_range, entry_artifact.machine_code.range);
        assert_eq!(record.entrypoint, entrypoint());
        assert_eq!(
            record.supported_opcode_subset,
            BaselineSupportedOpcodeSubset::P6ConstantsMovesReturnInt32Arithmetic
        );
        assert_eq!(
            record.effect_contract,
            BaselineSupportedOpcodeSubset::P6ConstantsMovesReturnInt32Arithmetic
                .generated_effect_contract()
        );
        assert_eq!(
            record.bytecode_snapshot,
            proof.bytecode_snapshot_fingerprint()
        );
        assert_eq!(record.source_buffer, buffer.id);
        assert_eq!(record.source_architecture, AssemblerArchitecture::X86_64);
        assert_eq!(record.source_image, image.id());
        assert_eq!(record.source_digest, image.digest());
        assert_eq!(
            record.source_size_bytes,
            CALLER_SUPPLIED_RECORD_BYTES.len() as u32
        );
        assert_eq!(record.linked_digest, linked.output_digest);
        assert_eq!(record.linked_size_bytes, linked.output_size_bytes);
        assert_eq!(record.linked_profile, LinkBufferProfile::Baseline);
        assert_eq!(record.linked_state, LinkBufferState::Linked);
        assert_eq!(record.relocation_count, 0);
        assert!(record.has_valid_baseline_abi_proof());
        assert_eq!(record.validate(), Ok(()));
    }

    #[test]
    fn p8b_emitter_kind_requires_exact_jump_if_false_subset() {
        let entry_artifact = entry_artifact();
        let proof = proof_for_subset(
            BaselineSupportedOpcodeSubset::P8bConstantsMovesReturnInt32ArithmeticBranchNullishFalse,
        );
        let buffer = frozen_buffer(AssemblerArchitecture::X86_64);
        let image = source_image(&buffer);
        let linked = linked_image(&buffer, &image);
        let mut p8b_request = request(&entry_artifact, &proof, &buffer, &image, Some(&linked));
        p8b_request.emitter_kind =
            BaselineMachineCodeEmitterKind::P8bX86_64NoCallNoHeapBranchTruthinessSubset;

        let record = record_baseline_machine_code_emission(p8b_request).unwrap();

        assert_eq!(
            record.emitter_kind,
            BaselineMachineCodeEmitterKind::P8bX86_64NoCallNoHeapBranchTruthinessSubset
        );
        assert_eq!(
            record.supported_opcode_subset,
            BaselineSupportedOpcodeSubset::P8bConstantsMovesReturnInt32ArithmeticBranchNullishFalse
        );
        assert_eq!(
            record.effect_contract,
            BaselineSupportedOpcodeSubset::P8bConstantsMovesReturnInt32ArithmeticBranchNullishFalse
                .generated_effect_contract()
        );

        let mut p8a_request = request(&entry_artifact, &proof, &buffer, &image, Some(&linked));
        p8a_request.emitter_kind =
            BaselineMachineCodeEmitterKind::P8aX86_64NoCallNoHeapBranchSubset;
        assert_eq!(
            record_baseline_machine_code_emission(p8a_request),
            Err(
                BaselineMachineCodeEmissionValidationError::UnsupportedOpcodeSubset {
                    emitter: BaselineMachineCodeEmitterKind::P8aX86_64NoCallNoHeapBranchSubset,
                    expected: BaselineSupportedOpcodeSubset::P8aConstantsMovesReturnInt32ArithmeticBranchNullish,
                    actual:
                        BaselineSupportedOpcodeSubset::P8bConstantsMovesReturnInt32ArithmeticBranchNullishFalse,
                },
            )
        );
    }

    #[test]
    fn bitand_or_emitter_kinds_require_exact_native_subsets() {
        let entry_artifact = entry_artifact();
        let buffer = frozen_buffer(AssemblerArchitecture::X86_64);
        let image = source_image(&buffer);
        let linked = linked_image(&buffer, &image);

        let proof = proof_for_subset(
            BaselineSupportedOpcodeSubset::P6ConstantsMovesReturnInt32ArithmeticBitAndOr,
        );
        let mut p6_request = request(&entry_artifact, &proof, &buffer, &image, Some(&linked));
        p6_request.emitter_kind =
            BaselineMachineCodeEmitterKind::P6X86_64NoCallNoHeapBitAndOrSubset;
        let record = record_baseline_machine_code_emission(p6_request).unwrap();
        assert_eq!(
            record.supported_opcode_subset,
            BaselineSupportedOpcodeSubset::P6ConstantsMovesReturnInt32ArithmeticBitAndOr
        );

        let proof = proof_for_subset(
            BaselineSupportedOpcodeSubset::P8bConstantsMovesReturnInt32ArithmeticBitAndOrBranchNullishFalse,
        );
        let mut p8b_request = request(&entry_artifact, &proof, &buffer, &image, Some(&linked));
        p8b_request.emitter_kind =
            BaselineMachineCodeEmitterKind::P8bX86_64NoCallNoHeapBitAndOrBranchTruthinessSubset;
        let record = record_baseline_machine_code_emission(p8b_request).unwrap();
        assert_eq!(
            record.supported_opcode_subset,
            BaselineSupportedOpcodeSubset::P8bConstantsMovesReturnInt32ArithmeticBitAndOrBranchNullishFalse
        );

        let proof = proof_for_subset(
            BaselineSupportedOpcodeSubset::P6ConstantsMovesReturnInt32ArithmeticBitAndOrEquality,
        );
        let mut p6_equality_request =
            request(&entry_artifact, &proof, &buffer, &image, Some(&linked));
        p6_equality_request.emitter_kind =
            BaselineMachineCodeEmitterKind::P6X86_64NoCallNoHeapBitAndOrEqualitySubset;
        let record = record_baseline_machine_code_emission(p6_equality_request).unwrap();
        assert_eq!(
            record.supported_opcode_subset,
            BaselineSupportedOpcodeSubset::P6ConstantsMovesReturnInt32ArithmeticBitAndOrEquality
        );

        let proof = proof_for_subset(
            BaselineSupportedOpcodeSubset::P8bConstantsMovesReturnInt32ArithmeticBitAndOrEqualityBranchNullishFalse,
        );
        let mut p8b_equality_request =
            request(&entry_artifact, &proof, &buffer, &image, Some(&linked));
        p8b_equality_request.emitter_kind =
            BaselineMachineCodeEmitterKind::P8bX86_64NoCallNoHeapBitAndOrEqualityBranchTruthinessSubset;
        let record = record_baseline_machine_code_emission(p8b_equality_request).unwrap();
        assert_eq!(
            record.supported_opcode_subset,
            BaselineSupportedOpcodeSubset::P8bConstantsMovesReturnInt32ArithmeticBitAndOrEqualityBranchNullishFalse
        );

        let proof = proof_for_subset(
            BaselineSupportedOpcodeSubset::P6ConstantsMovesReturnInt32ArithmeticBitAndOrEqualityRelational,
        );
        let mut p6_relational_request =
            request(&entry_artifact, &proof, &buffer, &image, Some(&linked));
        p6_relational_request.emitter_kind =
            BaselineMachineCodeEmitterKind::P6X86_64NoCallNoHeapBitAndOrEqualityRelationalSubset;
        let record = record_baseline_machine_code_emission(p6_relational_request).unwrap();
        assert_eq!(
            record.supported_opcode_subset,
            BaselineSupportedOpcodeSubset::P6ConstantsMovesReturnInt32ArithmeticBitAndOrEqualityRelational
        );

        let proof = proof_for_subset(
            BaselineSupportedOpcodeSubset::P8bConstantsMovesReturnInt32ArithmeticBitAndOrEqualityRelationalBranchNullishFalse,
        );
        let mut p8b_relational_request =
            request(&entry_artifact, &proof, &buffer, &image, Some(&linked));
        p8b_relational_request.emitter_kind =
            BaselineMachineCodeEmitterKind::P8bX86_64NoCallNoHeapBitAndOrEqualityRelationalBranchTruthinessSubset;
        let record = record_baseline_machine_code_emission(p8b_relational_request).unwrap();
        assert_eq!(
            record.supported_opcode_subset,
            BaselineSupportedOpcodeSubset::P8bConstantsMovesReturnInt32ArithmeticBitAndOrEqualityRelationalBranchNullishFalse
        );

        let no_call_loose_relational_proof = proof_for_subset(
            BaselineSupportedOpcodeSubset::P8bConstantsMovesReturnInt32ArithmeticBitAndOrNoCallLooseEqualityRelationalBranchNullishFalse,
        );
        let mut p8b_no_call_loose_relational_request = request(
            &entry_artifact,
            &no_call_loose_relational_proof,
            &buffer,
            &image,
            Some(&linked),
        );
        p8b_no_call_loose_relational_request.emitter_kind =
            BaselineMachineCodeEmitterKind::P8bX86_64NoCallNoHeapBitAndOrNoCallLooseEqualityRelationalBranchTruthinessSubset;
        let record =
            record_baseline_machine_code_emission(p8b_no_call_loose_relational_request).unwrap();
        assert_eq!(
            record.supported_opcode_subset,
            BaselineSupportedOpcodeSubset::P8bConstantsMovesReturnInt32ArithmeticBitAndOrNoCallLooseEqualityRelationalBranchNullishFalse
        );

        let mut wrong_request = request(&entry_artifact, &proof, &buffer, &image, Some(&linked));
        wrong_request.emitter_kind =
            BaselineMachineCodeEmitterKind::P8aX86_64NoCallNoHeapBitAndOrEqualityRelationalBranchSubset;
        assert_eq!(
            record_baseline_machine_code_emission(wrong_request),
            Err(
                BaselineMachineCodeEmissionValidationError::UnsupportedOpcodeSubset {
                    emitter:
                        BaselineMachineCodeEmitterKind::P8aX86_64NoCallNoHeapBitAndOrEqualityRelationalBranchSubset,
                    expected:
                        BaselineSupportedOpcodeSubset::P8aConstantsMovesReturnInt32ArithmeticBitAndOrEqualityRelationalBranchNullish,
                    actual:
                        BaselineSupportedOpcodeSubset::P8bConstantsMovesReturnInt32ArithmeticBitAndOrEqualityRelationalBranchNullishFalse,
                },
            )
        );
    }

    #[test]
    fn descriptor_only_or_missing_linked_image_is_rejected() {
        let (entry_artifact, proof, buffer, image, _linked) = accepted_parts();

        assert_eq!(
            record_baseline_machine_code_emission(request(
                &entry_artifact,
                &proof,
                &buffer,
                &image,
                None,
            )),
            Err(BaselineMachineCodeEmissionValidationError::LinkedImageMissing)
        );
    }

    #[test]
    fn wrong_source_architecture_is_rejected() {
        let entry_artifact = entry_artifact();
        let proof = proof();
        let buffer = frozen_buffer(AssemblerArchitecture::Arm64);
        let image = source_image(&buffer);
        let linked = linked_image(&buffer, &image);

        assert_eq!(
            record_baseline_machine_code_emission(request(
                &entry_artifact,
                &proof,
                &buffer,
                &image,
                Some(&linked),
            )),
            Err(
                BaselineMachineCodeEmissionValidationError::SourceArchitectureMismatch {
                    expected: AssemblerArchitecture::X86_64,
                    actual: Some(AssemblerArchitecture::Arm64),
                },
            )
        );
    }

    #[test]
    fn arm64_emitter_accepts_only_arm64_source_architecture() {
        let entry_artifact = entry_artifact();
        let proof = proof();
        let arm_buffer = frozen_buffer(AssemblerArchitecture::Arm64);
        let arm_image = source_image(&arm_buffer);
        let arm_linked = linked_image(&arm_buffer, &arm_image);

        let record = record_baseline_machine_code_emission(request_with_emitter(
            BaselineMachineCodeEmitterKind::P6Arm64NoCallNoHeapReturnSeedSubset,
            &entry_artifact,
            &proof,
            &arm_buffer,
            &arm_image,
            Some(&arm_linked),
        ))
        .expect("ARM64 emitter accepts ARM64 source bytes");
        assert_eq!(
            record.emitter_kind,
            BaselineMachineCodeEmitterKind::P6Arm64NoCallNoHeapReturnSeedSubset
        );
        assert_eq!(record.source_architecture, AssemblerArchitecture::Arm64);

        let x86_buffer = frozen_buffer(AssemblerArchitecture::X86_64);
        let x86_image = source_image(&x86_buffer);
        let x86_linked = linked_image(&x86_buffer, &x86_image);
        assert_eq!(
            record_baseline_machine_code_emission(request_with_emitter(
                BaselineMachineCodeEmitterKind::P6Arm64NoCallNoHeapReturnSeedSubset,
                &entry_artifact,
                &proof,
                &x86_buffer,
                &x86_image,
                Some(&x86_linked),
            )),
            Err(
                BaselineMachineCodeEmissionValidationError::SourceArchitectureMismatch {
                    expected: AssemblerArchitecture::Arm64,
                    actual: Some(AssemblerArchitecture::X86_64),
                },
            )
        );
    }

    #[test]
    fn relocation_count_nonzero_is_rejected() {
        let entry_artifact = entry_artifact();
        let proof = proof();
        let clean_buffer = frozen_buffer(AssemblerArchitecture::X86_64);
        let clean_image = source_image(&clean_buffer);
        let linked = linked_image(&clean_buffer, &clean_image);
        let relocated_buffer = frozen_buffer_with_relocation();
        let relocated_image = source_image(&relocated_buffer);

        assert_eq!(
            record_baseline_machine_code_emission(request(
                &entry_artifact,
                &proof,
                &relocated_buffer,
                &relocated_image,
                Some(&linked),
            )),
            Err(
                BaselineMachineCodeEmissionValidationError::RelocationsUnsupported {
                    source: BaselineMachineCodeEmissionRelocationSource::SourceBuffer,
                    actual: 1,
                },
            )
        );

        let (entry_artifact, proof, buffer, image, mut linked) = accepted_parts();
        linked.relocation_count = 1;
        assert_eq!(
            record_baseline_machine_code_emission(request(
                &entry_artifact,
                &proof,
                &buffer,
                &image,
                Some(&linked),
            )),
            Err(
                BaselineMachineCodeEmissionValidationError::RelocationsUnsupported {
                    source: BaselineMachineCodeEmissionRelocationSource::LinkedImage,
                    actual: 1,
                },
            )
        );
    }

    #[test]
    fn linked_digest_or_length_mismatch_is_rejected() {
        let (entry_artifact, proof, buffer, image, mut linked) = accepted_parts();
        linked.output_digest = AssemblerByteImageDigest(0xfeed);

        assert_eq!(
            record_baseline_machine_code_emission(request(
                &entry_artifact,
                &proof,
                &buffer,
                &image,
                Some(&linked),
            )),
            Err(
                BaselineMachineCodeEmissionValidationError::LinkedImageInvalid {
                    error: AssemblerValidationError::AssemblerByteImageDigestMismatch {
                        expected: AssemblerByteImageDigest(0xfeed),
                        actual: image.digest(),
                    },
                },
            )
        );

        let (entry_artifact, proof, buffer, image, mut linked) = accepted_parts();
        linked.output_size_bytes += 1;
        assert_eq!(
            record_baseline_machine_code_emission(request(
                &entry_artifact,
                &proof,
                &buffer,
                &image,
                Some(&linked),
            )),
            Err(
                BaselineMachineCodeEmissionValidationError::LinkedImageInvalid {
                    error: AssemblerValidationError::AssemblerByteImageBytesLengthMismatch {
                        expected: CALLER_SUPPLIED_RECORD_BYTES.len() as u32 + 1,
                        actual: CALLER_SUPPLIED_RECORD_BYTES.len(),
                    },
                },
            )
        );
    }

    #[test]
    fn writable_machine_code_metadata_is_accepted_as_byte_shape_provenance() {
        let (mut entry_artifact, proof, buffer, image, linked) = accepted_parts();
        entry_artifact.machine_code.protection = ExecutableMemoryProtection::Writable;
        entry_artifact.machine_code.lifecycle = ExecutableAllocationLifecycle::AllocatedWritable;

        let record = record_baseline_machine_code_emission(request(
            &entry_artifact,
            &proof,
            &buffer,
            &image,
            Some(&linked),
        ))
        .unwrap();

        assert_eq!(
            record.machine_code.protection,
            ExecutableMemoryProtection::Writable
        );
        assert_eq!(
            record.machine_code.lifecycle,
            ExecutableAllocationLifecycle::AllocatedWritable
        );
        assert_eq!(record.validate(), Ok(()));
    }

    #[test]
    fn invalid_machine_code_protection_lifecycle_pair_is_rejected() {
        let (mut entry_artifact, proof, buffer, image, linked) = accepted_parts();
        entry_artifact.machine_code.protection = ExecutableMemoryProtection::Writable;

        assert_eq!(
            record_baseline_machine_code_emission(request(
                &entry_artifact,
                &proof,
                &buffer,
                &image,
                Some(&linked),
            )),
            Err(
                BaselineMachineCodeEmissionValidationError::MachineCodeInvalid {
                    error: MachineCodeValidationError::ProtectionLifecycleMismatch,
                }
            )
        );
    }

    #[test]
    fn entrypoint_mismatch_is_rejected() {
        let (mut entry_artifact, proof, buffer, image, linked) = accepted_parts();
        entry_artifact.entrypoint.code = Some(JitCodeId(999));

        assert_eq!(
            record_baseline_machine_code_emission(request(
                &entry_artifact,
                &proof,
                &buffer,
                &image,
                Some(&linked),
            )),
            Err(
                BaselineMachineCodeEmissionValidationError::ArtifactInvalid {
                    error: JitCodeValidationError::BaselineEntryEntrypointMissing,
                }
            )
        );
    }

    #[test]
    fn unsupported_opcode_subset_or_effect_contract_is_rejected() {
        let entry_artifact = entry_artifact();
        let proof = proof_for_subset(
            BaselineSupportedOpcodeSubset::P6ConstantsMovesReturnInt32ArithmeticBitwise,
        );
        let buffer = frozen_buffer(AssemblerArchitecture::X86_64);
        let image = source_image(&buffer);
        let linked = linked_image(&buffer, &image);

        assert_eq!(
            record_baseline_machine_code_emission(request(
                &entry_artifact,
                &proof,
                &buffer,
                &image,
                Some(&linked),
            )),
            Err(
                BaselineMachineCodeEmissionValidationError::UnsupportedOpcodeSubset {
                    emitter: BaselineMachineCodeEmitterKind::P6X86_64NoCallNoHeapSubset,
                    expected: BaselineSupportedOpcodeSubset::P6ConstantsMovesReturnInt32Arithmetic,
                    actual:
                        BaselineSupportedOpcodeSubset::P6ConstantsMovesReturnInt32ArithmeticBitwise,
                },
            )
        );

        let (entry_artifact, proof, buffer, image, linked) = accepted_parts();
        let mut record = record_baseline_machine_code_emission(request(
            &entry_artifact,
            &proof,
            &buffer,
            &image,
            Some(&linked),
        ))
        .unwrap();
        record.effect_contract.summary.may_call_js = true;
        record.proof.effect_contract = record.effect_contract;

        assert_eq!(
            record.validate(),
            Err(
                BaselineMachineCodeEmissionValidationError::UnsupportedEffectContract {
                    emitter: BaselineMachineCodeEmitterKind::P6X86_64NoCallNoHeapSubset,
                    expected: BaselineSupportedOpcodeSubset::P6ConstantsMovesReturnInt32Arithmetic
                        .generated_effect_contract(),
                    actual: record.effect_contract,
                },
            )
        );
    }
}
